// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_pool_assignments.sql

package queries

import (
	"context"
	"database/sql"
)

const countActiveStreamsForAccount = `-- name: CountActiveStreamsForAccount :one
SELECT COUNT(*)
FROM playback_events
WHERE account_id = ?
  AND operation = 'stream'
  AND finished_at IS NULL
  AND started_at >= ?
`

type CountActiveStreamsForAccountParams struct {
	AccountID sql.NullString `json:"account_id"`
	StartedAt int64          `json:"started_at"`
}

func (q *Queries) CountActiveStreamsForAccount(ctx context.Context, arg CountActiveStreamsForAccountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveStreamsForAccount, arg.AccountID, arg.StartedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccountPoolAssignment = `-- name: CreateAccountPoolAssignment :one
INSERT INTO account_pool_assignments (
  echo_user_id, account_id, provider, priority, weight, max_concurrent_streams,
  daily_bytes_limit, enabled, created_at, updated_at
)
SELECT
  ?1, accounts.id, accounts.provider, ?2,
  ?3, ?4, ?5,
  ?6, ?7, ?8
FROM accounts
WHERE accounts.id = ?9
  AND accounts.provider = ?10
RETURNING id, echo_user_id, account_id, provider, priority, weight, max_concurrent_streams, daily_bytes_limit, enabled, created_at, updated_at
`

type CreateAccountPoolAssignmentParams struct {
	EchoUserID           string        `json:"echo_user_id"`
	Priority             int64         `json:"priority"`
	Weight               int64         `json:"weight"`
	MaxConcurrentStreams sql.NullInt64 `json:"max_concurrent_streams"`
	DailyBytesLimit      sql.NullInt64 `json:"daily_bytes_limit"`
	Enabled              int64         `json:"enabled"`
	CreatedAt            int64         `json:"created_at"`
	UpdatedAt            int64         `json:"updated_at"`
	AccountID            string        `json:"account_id"`
	Provider             string        `json:"provider"`
}

func (q *Queries) CreateAccountPoolAssignment(ctx context.Context, arg CreateAccountPoolAssignmentParams) (AccountPoolAssignment, error) {
	row := q.db.QueryRowContext(ctx, createAccountPoolAssignment,
		arg.EchoUserID,
		arg.Priority,
		arg.Weight,
		arg.MaxConcurrentStreams,
		arg.DailyBytesLimit,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.AccountID,
		arg.Provider,
	)
	var i AccountPoolAssignment
	err := row.Scan(
		&i.ID,
		&i.EchoUserID,
		&i.AccountID,
		&i.Provider,
		&i.Priority,
		&i.Weight,
		&i.MaxConcurrentStreams,
		&i.DailyBytesLimit,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlayableCopiesForUser = `-- name: ListPlayableCopiesForUser :many
SELECT
  fc.id, fc.blob_id, fc.provider, fc.account_id, fc.sidecar_id, fc.storage_mount,
  fc.remote_path, fc.cloud_file_id, fc.pickcode, fc.status, fc.last_seen,
  fc.scheduler_state, fc.cooldown_until, fc.verify_after, fc.failure_count,
  fc.last_failure_at, fc.last_failure_kind, fc.last_failure_confidence,
  fc.last_failure_code, fc.last_failure_message, fc.dead_reason, fc.dead_at,
  apa.priority, apa.weight, apa.max_concurrent_streams, apa.daily_bytes_limit,
  CAST(CASE WHEN fc.provider = ?1 THEN 0 ELSE 1 END AS INTEGER) AS provider_rank
FROM file_copies fc
JOIN account_pool_assignments apa ON apa.account_id = fc.account_id
JOIN accounts a ON a.id = fc.account_id
WHERE fc.blob_id = ?2
  AND apa.echo_user_id = ?3
  AND apa.provider = a.provider
  AND apa.provider = fc.provider
  AND apa.enabled = 1
  AND fc.status = 'live'
  AND fc.scheduler_state NOT IN ('confirmed_dead','suspect_dead')
  AND (fc.cooldown_until IS NULL OR fc.cooldown_until <= ?4)
  AND a.status NOT IN ('disabled','deleted')
  AND a.scheduler_state NOT IN ('cooldown','unhealthy','token_suspect','disabled')
  AND (a.cooldown_until IS NULL OR a.cooldown_until <= ?4)
  AND (
    apa.max_concurrent_streams IS NULL OR
    (
      SELECT COUNT(*) FROM playback_events pe
      WHERE pe.account_id = fc.account_id
        AND pe.operation = 'stream'
        AND pe.finished_at IS NULL
        AND pe.started_at >= ?5
    ) < apa.max_concurrent_streams
  )
  AND (
    apa.daily_bytes_limit IS NULL OR
    (
      SELECT COALESCE(SUM(pe.bytes_sent), 0) FROM playback_events pe
      WHERE pe.account_id = fc.account_id
        AND pe.operation = 'stream'
        AND pe.started_at >= ?6
        AND pe.started_at < ?7
        AND pe.bytes_sent > 0
        AND pe.status IN ('ok','interrupted','failed','upstream_read_error')
    ) < apa.daily_bytes_limit
  )
ORDER BY provider_rank ASC, apa.priority ASC, fc.last_seen DESC
LIMIT ?8
`

type ListPlayableCopiesForUserParams struct {
	PreferProvider string        `json:"prefer_provider"`
	BlobID         int64         `json:"blob_id"`
	EchoUserID     string        `json:"echo_user_id"`
	Now            sql.NullInt64 `json:"now"`
	ActiveSince    int64         `json:"active_since"`
	DayStart       int64         `json:"day_start"`
	DayEnd         int64         `json:"day_end"`
	Limit          int64         `json:"limit"`
}

type ListPlayableCopiesForUserRow struct {
	ID                    int64          `json:"id"`
	BlobID                int64          `json:"blob_id"`
	Provider              string         `json:"provider"`
	AccountID             string         `json:"account_id"`
	SidecarID             string         `json:"sidecar_id"`
	StorageMount          string         `json:"storage_mount"`
	RemotePath            string         `json:"remote_path"`
	CloudFileID           sql.NullString `json:"cloud_file_id"`
	Pickcode              sql.NullString `json:"pickcode"`
	Status                string         `json:"status"`
	LastSeen              int64          `json:"last_seen"`
	SchedulerState        string         `json:"scheduler_state"`
	CooldownUntil         sql.NullInt64  `json:"cooldown_until"`
	VerifyAfter           sql.NullInt64  `json:"verify_after"`
	FailureCount          int64          `json:"failure_count"`
	LastFailureAt         sql.NullInt64  `json:"last_failure_at"`
	LastFailureKind       sql.NullString `json:"last_failure_kind"`
	LastFailureConfidence sql.NullString `json:"last_failure_confidence"`
	LastFailureCode       sql.NullInt64  `json:"last_failure_code"`
	LastFailureMessage    sql.NullString `json:"last_failure_message"`
	DeadReason            sql.NullString `json:"dead_reason"`
	DeadAt                sql.NullInt64  `json:"dead_at"`
	Priority              int64          `json:"priority"`
	Weight                int64          `json:"weight"`
	MaxConcurrentStreams  sql.NullInt64  `json:"max_concurrent_streams"`
	DailyBytesLimit       sql.NullInt64  `json:"daily_bytes_limit"`
	ProviderRank          int64          `json:"provider_rank"`
}

func (q *Queries) ListPlayableCopiesForUser(ctx context.Context, arg ListPlayableCopiesForUserParams) ([]ListPlayableCopiesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayableCopiesForUser,
		arg.PreferProvider,
		arg.BlobID,
		arg.EchoUserID,
		arg.Now,
		arg.ActiveSince,
		arg.DayStart,
		arg.DayEnd,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayableCopiesForUserRow
	for rows.Next() {
		var i ListPlayableCopiesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.BlobID,
			&i.Provider,
			&i.AccountID,
			&i.SidecarID,
			&i.StorageMount,
			&i.RemotePath,
			&i.CloudFileID,
			&i.Pickcode,
			&i.Status,
			&i.LastSeen,
			&i.SchedulerState,
			&i.CooldownUntil,
			&i.VerifyAfter,
			&i.FailureCount,
			&i.LastFailureAt,
			&i.LastFailureKind,
			&i.LastFailureConfidence,
			&i.LastFailureCode,
			&i.LastFailureMessage,
			&i.DeadReason,
			&i.DeadAt,
			&i.Priority,
			&i.Weight,
			&i.MaxConcurrentStreams,
			&i.DailyBytesLimit,
			&i.ProviderRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumAccountPlaybackBytesInWindow = `-- name: SumAccountPlaybackBytesInWindow :one
SELECT CAST(COALESCE(SUM(bytes_sent), 0) AS INTEGER) AS bytes
FROM playback_events
WHERE account_id = ?
  AND operation = 'stream'
  AND started_at >= ?
  AND started_at < ?
  AND bytes_sent > 0
  AND status IN ('ok','interrupted','failed','upstream_read_error')
`

type SumAccountPlaybackBytesInWindowParams struct {
	AccountID   sql.NullString `json:"account_id"`
	StartedAt   int64          `json:"started_at"`
	StartedAt_2 int64          `json:"started_at_2"`
}

func (q *Queries) SumAccountPlaybackBytesInWindow(ctx context.Context, arg SumAccountPlaybackBytesInWindowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumAccountPlaybackBytesInWindow, arg.AccountID, arg.StartedAt, arg.StartedAt_2)
	var bytes int64
	err := row.Scan(&bytes)
	return bytes, err
}
