// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package queries

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (
  id, provider, sidecar_id, storage_mount, status, last_check, owner_id, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateAccountParams struct {
	ID           string        `json:"id"`
	Provider     string        `json:"provider"`
	SidecarID    string        `json:"sidecar_id"`
	StorageMount string        `json:"storage_mount"`
	Status       string        `json:"status"`
	LastCheck    sql.NullInt64 `json:"last_check"`
	OwnerID      string        `json:"owner_id"`
	CreatedAt    int64         `json:"created_at"`
	UpdatedAt    int64         `json:"updated_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount,
		arg.ID,
		arg.Provider,
		arg.SidecarID,
		arg.StorageMount,
		arg.Status,
		arg.LastCheck,
		arg.OwnerID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts
WHERE id = ?
`

type DeleteAccountParams struct {
	ID string `json:"id"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, arg.ID)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, provider, sidecar_id, storage_mount, status, last_check, owner_id, created_at, updated_at, scheduler_state, cooldown_until, recheck_after, status_reason, last_error_at, last_error_kind, last_error_message FROM accounts
WHERE id = ?
`

type GetAccountParams struct {
	ID string `json:"id"`
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.SidecarID,
		&i.StorageMount,
		&i.Status,
		&i.LastCheck,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SchedulerState,
		&i.CooldownUntil,
		&i.RecheckAfter,
		&i.StatusReason,
		&i.LastErrorAt,
		&i.LastErrorKind,
		&i.LastErrorMessage,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, provider, sidecar_id, storage_mount, status, last_check, owner_id, created_at, updated_at, scheduler_state, cooldown_until, recheck_after, status_reason, last_error_at, last_error_kind, last_error_message FROM accounts
ORDER BY id
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.SidecarID,
			&i.StorageMount,
			&i.Status,
			&i.LastCheck,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SchedulerState,
			&i.CooldownUntil,
			&i.RecheckAfter,
			&i.StatusReason,
			&i.LastErrorAt,
			&i.LastErrorKind,
			&i.LastErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAccountSchedulerState = `-- name: MarkAccountSchedulerState :exec
UPDATE accounts
SET scheduler_state = ?,
    cooldown_until = ?,
    recheck_after = ?,
    status_reason = ?,
    last_error_at = ?,
    last_error_kind = ?,
    last_error_message = ?,
    updated_at = ?
WHERE id = ?
`

type MarkAccountSchedulerStateParams struct {
	SchedulerState   string         `json:"scheduler_state"`
	CooldownUntil    sql.NullInt64  `json:"cooldown_until"`
	RecheckAfter     sql.NullInt64  `json:"recheck_after"`
	StatusReason     sql.NullString `json:"status_reason"`
	LastErrorAt      sql.NullInt64  `json:"last_error_at"`
	LastErrorKind    sql.NullString `json:"last_error_kind"`
	LastErrorMessage sql.NullString `json:"last_error_message"`
	UpdatedAt        int64          `json:"updated_at"`
	ID               string         `json:"id"`
}

func (q *Queries) MarkAccountSchedulerState(ctx context.Context, arg MarkAccountSchedulerStateParams) error {
	_, err := q.db.ExecContext(ctx, markAccountSchedulerState,
		arg.SchedulerState,
		arg.CooldownUntil,
		arg.RecheckAfter,
		arg.StatusReason,
		arg.LastErrorAt,
		arg.LastErrorKind,
		arg.LastErrorMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts
SET provider = ?,
    sidecar_id = ?,
    storage_mount = ?,
    status = ?,
    last_check = ?,
    owner_id = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateAccountParams struct {
	Provider     string        `json:"provider"`
	SidecarID    string        `json:"sidecar_id"`
	StorageMount string        `json:"storage_mount"`
	Status       string        `json:"status"`
	LastCheck    sql.NullInt64 `json:"last_check"`
	OwnerID      string        `json:"owner_id"`
	UpdatedAt    int64         `json:"updated_at"`
	ID           string        `json:"id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateAccount,
		arg.Provider,
		arg.SidecarID,
		arg.StorageMount,
		arg.Status,
		arg.LastCheck,
		arg.OwnerID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :exec
UPDATE accounts
SET status = ?, last_check = ?, updated_at = ?
WHERE id = ?
`

type UpdateAccountStatusParams struct {
	Status    string        `json:"status"`
	LastCheck sql.NullInt64 `json:"last_check"`
	UpdatedAt int64         `json:"updated_at"`
	ID        string        `json:"id"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountStatus,
		arg.Status,
		arg.LastCheck,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
