// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blob_hashes.sql

package queries

import (
	"context"
)

const getBlobHashByKey = `-- name: GetBlobHashByKey :one
SELECT id, blob_id, hash_type, hash_value, hash_value_norm, size FROM blob_hashes
WHERE hash_type = ? AND hash_value_norm = ? AND size = ?
`

type GetBlobHashByKeyParams struct {
	HashType      string `json:"hash_type"`
	HashValueNorm string `json:"hash_value_norm"`
	Size          int64  `json:"size"`
}

func (q *Queries) GetBlobHashByKey(ctx context.Context, arg GetBlobHashByKeyParams) (BlobHash, error) {
	row := q.db.QueryRowContext(ctx, getBlobHashByKey, arg.HashType, arg.HashValueNorm, arg.Size)
	var i BlobHash
	err := row.Scan(
		&i.ID,
		&i.BlobID,
		&i.HashType,
		&i.HashValue,
		&i.HashValueNorm,
		&i.Size,
	)
	return i, err
}

const insertBlobHash = `-- name: InsertBlobHash :one
INSERT INTO blob_hashes (
  blob_id, hash_type, hash_value, hash_value_norm, size
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id, blob_id, hash_type, hash_value, hash_value_norm, size
`

type InsertBlobHashParams struct {
	BlobID        int64  `json:"blob_id"`
	HashType      string `json:"hash_type"`
	HashValue     string `json:"hash_value"`
	HashValueNorm string `json:"hash_value_norm"`
	Size          int64  `json:"size"`
}

func (q *Queries) InsertBlobHash(ctx context.Context, arg InsertBlobHashParams) (BlobHash, error) {
	row := q.db.QueryRowContext(ctx, insertBlobHash,
		arg.BlobID,
		arg.HashType,
		arg.HashValue,
		arg.HashValueNorm,
		arg.Size,
	)
	var i BlobHash
	err := row.Scan(
		&i.ID,
		&i.BlobID,
		&i.HashType,
		&i.HashValue,
		&i.HashValueNorm,
		&i.Size,
	)
	return i, err
}

const listBlobHashesByBlob = `-- name: ListBlobHashesByBlob :many
SELECT id, blob_id, hash_type, hash_value, hash_value_norm, size FROM blob_hashes
WHERE blob_id = ?
ORDER BY id
`

type ListBlobHashesByBlobParams struct {
	BlobID int64 `json:"blob_id"`
}

func (q *Queries) ListBlobHashesByBlob(ctx context.Context, arg ListBlobHashesByBlobParams) ([]BlobHash, error) {
	rows, err := q.db.QueryContext(ctx, listBlobHashesByBlob, arg.BlobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlobHash
	for rows.Next() {
		var i BlobHash
		if err := rows.Scan(
			&i.ID,
			&i.BlobID,
			&i.HashType,
			&i.HashValue,
			&i.HashValueNorm,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
