// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blobs.sql

package queries

import (
	"context"
	"database/sql"
)

const createBlob = `-- name: CreateBlob :one
INSERT INTO blobs (
  size, canonical_name, source_mtime, owner_id, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?
)
RETURNING id, size, canonical_name, source_mtime, owner_id, created_at, updated_at
`

type CreateBlobParams struct {
	Size          int64          `json:"size"`
	CanonicalName sql.NullString `json:"canonical_name"`
	SourceMtime   sql.NullInt64  `json:"source_mtime"`
	OwnerID       string         `json:"owner_id"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

func (q *Queries) CreateBlob(ctx context.Context, arg CreateBlobParams) (Blob, error) {
	row := q.db.QueryRowContext(ctx, createBlob,
		arg.Size,
		arg.CanonicalName,
		arg.SourceMtime,
		arg.OwnerID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Blob
	err := row.Scan(
		&i.ID,
		&i.Size,
		&i.CanonicalName,
		&i.SourceMtime,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBlob = `-- name: DeleteBlob :exec
DELETE FROM blobs
WHERE id = ?
`

type DeleteBlobParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) DeleteBlob(ctx context.Context, arg DeleteBlobParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlob, arg.ID)
	return err
}

const getBlob = `-- name: GetBlob :one
SELECT id, size, canonical_name, source_mtime, owner_id, created_at, updated_at FROM blobs
WHERE id = ?
`

type GetBlobParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetBlob(ctx context.Context, arg GetBlobParams) (Blob, error) {
	row := q.db.QueryRowContext(ctx, getBlob, arg.ID)
	var i Blob
	err := row.Scan(
		&i.ID,
		&i.Size,
		&i.CanonicalName,
		&i.SourceMtime,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBlobs = `-- name: ListBlobs :many
SELECT id, size, canonical_name, source_mtime, owner_id, created_at, updated_at FROM blobs
ORDER BY id
LIMIT ? OFFSET ?
`

type ListBlobsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListBlobs(ctx context.Context, arg ListBlobsParams) ([]Blob, error) {
	rows, err := q.db.QueryContext(ctx, listBlobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blob
	for rows.Next() {
		var i Blob
		if err := rows.Scan(
			&i.ID,
			&i.Size,
			&i.CanonicalName,
			&i.SourceMtime,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
