// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copy_failures.sql

package queries

import (
	"context"
	"database/sql"
)

const insertCopyFailure = `-- name: InsertCopyFailure :exec
INSERT INTO copy_failures (
  copy_id, account_id, sidecar_id, storage_mount, operation, kind, confidence,
  evidence_class, http_status, openlist_code, safe_message, observed_at, request_id
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertCopyFailureParams struct {
	CopyID        sql.NullInt64  `json:"copy_id"`
	AccountID     sql.NullString `json:"account_id"`
	SidecarID     string         `json:"sidecar_id"`
	StorageMount  string         `json:"storage_mount"`
	Operation     string         `json:"operation"`
	Kind          string         `json:"kind"`
	Confidence    string         `json:"confidence"`
	EvidenceClass string         `json:"evidence_class"`
	HttpStatus    sql.NullInt64  `json:"http_status"`
	OpenlistCode  sql.NullInt64  `json:"openlist_code"`
	SafeMessage   sql.NullString `json:"safe_message"`
	ObservedAt    int64          `json:"observed_at"`
	RequestID     sql.NullString `json:"request_id"`
}

func (q *Queries) InsertCopyFailure(ctx context.Context, arg InsertCopyFailureParams) error {
	_, err := q.db.ExecContext(ctx, insertCopyFailure,
		arg.CopyID,
		arg.AccountID,
		arg.SidecarID,
		arg.StorageMount,
		arg.Operation,
		arg.Kind,
		arg.Confidence,
		arg.EvidenceClass,
		arg.HttpStatus,
		arg.OpenlistCode,
		arg.SafeMessage,
		arg.ObservedAt,
		arg.RequestID,
	)
	return err
}
