// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discovery_telegram.sql

package queries

import (
	"context"
	"database/sql"
)

const backoffTelegramChannel = `-- name: BackoffTelegramChannel :exec
UPDATE telegram_channels
SET backoff_until = ?, failure_count = failure_count + 1,
    last_error_kind = ?, last_error_message = ?, locked_until = NULL,
    updated_at = ?
WHERE id = ?
`

type BackoffTelegramChannelParams struct {
	BackoffUntil     sql.NullInt64  `json:"backoff_until"`
	LastErrorKind    sql.NullString `json:"last_error_kind"`
	LastErrorMessage sql.NullString `json:"last_error_message"`
	UpdatedAt        int64          `json:"updated_at"`
	ID               int64          `json:"id"`
}

func (q *Queries) BackoffTelegramChannel(ctx context.Context, arg BackoffTelegramChannelParams) error {
	_, err := q.db.ExecContext(ctx, backoffTelegramChannel,
		arg.BackoffUntil,
		arg.LastErrorKind,
		arg.LastErrorMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const createTelegramChannel = `-- name: CreateTelegramChannel :one
INSERT INTO telegram_channels (
  source_id, channel_ref, stable_peer_id, username_snapshot, title_snapshot,
  level_flags, enabled, last_message_id, last_message_date, next_run_at,
  created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, source_id, channel_ref, stable_peer_id, username_snapshot, title_snapshot, level_flags, enabled, last_message_id, last_message_date, next_run_at, locked_until, backoff_until, failure_count, last_error_kind, last_error_message, created_at, updated_at
`

type CreateTelegramChannelParams struct {
	SourceID         int64          `json:"source_id"`
	ChannelRef       string         `json:"channel_ref"`
	StablePeerID     sql.NullString `json:"stable_peer_id"`
	UsernameSnapshot sql.NullString `json:"username_snapshot"`
	TitleSnapshot    sql.NullString `json:"title_snapshot"`
	LevelFlags       int64          `json:"level_flags"`
	Enabled          int64          `json:"enabled"`
	LastMessageID    sql.NullInt64  `json:"last_message_id"`
	LastMessageDate  sql.NullInt64  `json:"last_message_date"`
	NextRunAt        sql.NullInt64  `json:"next_run_at"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

func (q *Queries) CreateTelegramChannel(ctx context.Context, arg CreateTelegramChannelParams) (TelegramChannel, error) {
	row := q.db.QueryRowContext(ctx, createTelegramChannel,
		arg.SourceID,
		arg.ChannelRef,
		arg.StablePeerID,
		arg.UsernameSnapshot,
		arg.TitleSnapshot,
		arg.LevelFlags,
		arg.Enabled,
		arg.LastMessageID,
		arg.LastMessageDate,
		arg.NextRunAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TelegramChannel
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ChannelRef,
		&i.StablePeerID,
		&i.UsernameSnapshot,
		&i.TitleSnapshot,
		&i.LevelFlags,
		&i.Enabled,
		&i.LastMessageID,
		&i.LastMessageDate,
		&i.NextRunAt,
		&i.LockedUntil,
		&i.BackoffUntil,
		&i.FailureCount,
		&i.LastErrorKind,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const leaseDueTelegramChannels = `-- name: LeaseDueTelegramChannels :many
UPDATE telegram_channels
SET locked_until = ?, updated_at = ?
WHERE id IN (
  SELECT tc.id FROM telegram_channels AS tc
  WHERE tc.source_id = ?
    AND tc.enabled = 1
    AND (tc.next_run_at IS NULL OR tc.next_run_at <= ?)
    AND (tc.locked_until IS NULL OR tc.locked_until <= ?)
    AND (tc.backoff_until IS NULL OR tc.backoff_until <= ?)
  ORDER BY COALESCE(tc.next_run_at, 0), tc.id
  LIMIT ?
)
RETURNING id, source_id, channel_ref, stable_peer_id, username_snapshot, title_snapshot, level_flags, enabled, last_message_id, last_message_date, next_run_at, locked_until, backoff_until, failure_count, last_error_kind, last_error_message, created_at, updated_at
`

type LeaseDueTelegramChannelsParams struct {
	LockedUntil   sql.NullInt64 `json:"locked_until"`
	UpdatedAt     int64         `json:"updated_at"`
	SourceID      int64         `json:"source_id"`
	NextRunAt     sql.NullInt64 `json:"next_run_at"`
	LockedUntil_2 sql.NullInt64 `json:"locked_until_2"`
	BackoffUntil  sql.NullInt64 `json:"backoff_until"`
	Limit         int64         `json:"limit"`
}

func (q *Queries) LeaseDueTelegramChannels(ctx context.Context, arg LeaseDueTelegramChannelsParams) ([]TelegramChannel, error) {
	rows, err := q.db.QueryContext(ctx, leaseDueTelegramChannels,
		arg.LockedUntil,
		arg.UpdatedAt,
		arg.SourceID,
		arg.NextRunAt,
		arg.LockedUntil_2,
		arg.BackoffUntil,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TelegramChannel
	for rows.Next() {
		var i TelegramChannel
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ChannelRef,
			&i.StablePeerID,
			&i.UsernameSnapshot,
			&i.TitleSnapshot,
			&i.LevelFlags,
			&i.Enabled,
			&i.LastMessageID,
			&i.LastMessageDate,
			&i.NextRunAt,
			&i.LockedUntil,
			&i.BackoffUntil,
			&i.FailureCount,
			&i.LastErrorKind,
			&i.LastErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTelegramChannelsBySource = `-- name: ListTelegramChannelsBySource :many
SELECT id, source_id, channel_ref, stable_peer_id, username_snapshot, title_snapshot, level_flags, enabled, last_message_id, last_message_date, next_run_at, locked_until, backoff_until, failure_count, last_error_kind, last_error_message, created_at, updated_at FROM telegram_channels
WHERE source_id = ?
ORDER BY id
`

type ListTelegramChannelsBySourceParams struct {
	SourceID int64 `json:"source_id"`
}

func (q *Queries) ListTelegramChannelsBySource(ctx context.Context, arg ListTelegramChannelsBySourceParams) ([]TelegramChannel, error) {
	rows, err := q.db.QueryContext(ctx, listTelegramChannelsBySource, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TelegramChannel
	for rows.Next() {
		var i TelegramChannel
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ChannelRef,
			&i.StablePeerID,
			&i.UsernameSnapshot,
			&i.TitleSnapshot,
			&i.LevelFlags,
			&i.Enabled,
			&i.LastMessageID,
			&i.LastMessageDate,
			&i.NextRunAt,
			&i.LockedUntil,
			&i.BackoffUntil,
			&i.FailureCount,
			&i.LastErrorKind,
			&i.LastErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTelegramChannelCursor = `-- name: UpdateTelegramChannelCursor :exec
UPDATE telegram_channels
SET last_message_id = ?, last_message_date = ?, failure_count = 0,
    last_error_kind = NULL, last_error_message = NULL, locked_until = NULL,
    updated_at = ?
WHERE id = ?
`

type UpdateTelegramChannelCursorParams struct {
	LastMessageID   sql.NullInt64 `json:"last_message_id"`
	LastMessageDate sql.NullInt64 `json:"last_message_date"`
	UpdatedAt       int64         `json:"updated_at"`
	ID              int64         `json:"id"`
}

func (q *Queries) UpdateTelegramChannelCursor(ctx context.Context, arg UpdateTelegramChannelCursorParams) error {
	_, err := q.db.ExecContext(ctx, updateTelegramChannelCursor,
		arg.LastMessageID,
		arg.LastMessageDate,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
