// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discovery_sources.sql

package queries

import (
	"context"
	"database/sql"
)

const backoffDiscoverySource = `-- name: BackoffDiscoverySource :exec
UPDATE discovery_sources
SET locked_until = NULL, scheduler_state = 'backoff', backoff_until = ?,
    failure_count = failure_count + 1, last_error_kind = ?,
    last_error_message = ?, updated_at = ?
WHERE id = ?
`

type BackoffDiscoverySourceParams struct {
	BackoffUntil     sql.NullInt64  `json:"backoff_until"`
	LastErrorKind    sql.NullString `json:"last_error_kind"`
	LastErrorMessage sql.NullString `json:"last_error_message"`
	UpdatedAt        int64          `json:"updated_at"`
	ID               int64          `json:"id"`
}

func (q *Queries) BackoffDiscoverySource(ctx context.Context, arg BackoffDiscoverySourceParams) error {
	_, err := q.db.ExecContext(ctx, backoffDiscoverySource,
		arg.BackoffUntil,
		arg.LastErrorKind,
		arg.LastErrorMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const clearDiscoverySourceLease = `-- name: ClearDiscoverySourceLease :exec
UPDATE discovery_sources
SET locked_until = NULL, scheduler_state = 'healthy', backoff_until = NULL, failure_count = 0,
    last_success_at = ?, last_error_kind = NULL, last_error_message = NULL,
    next_run_at = ?, updated_at = ?
WHERE id = ?
`

type ClearDiscoverySourceLeaseParams struct {
	LastSuccessAt sql.NullInt64 `json:"last_success_at"`
	NextRunAt     sql.NullInt64 `json:"next_run_at"`
	UpdatedAt     int64         `json:"updated_at"`
	ID            int64         `json:"id"`
}

func (q *Queries) ClearDiscoverySourceLease(ctx context.Context, arg ClearDiscoverySourceLeaseParams) error {
	_, err := q.db.ExecContext(ctx, clearDiscoverySourceLease,
		arg.LastSuccessAt,
		arg.NextRunAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const createDiscoverySource = `-- name: CreateDiscoverySource :one
INSERT INTO discovery_sources (
  kind, name, enabled, config_json, secret_ref, rate_limit_json,
  scheduler_state, next_run_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, 'healthy', ?, ?, ?)
RETURNING id, kind, name, enabled, config_json, secret_ref, rate_limit_json, scheduler_state, next_run_at, locked_until, backoff_until, failure_count, last_success_at, last_error_kind, last_error_message, created_at, updated_at
`

type CreateDiscoverySourceParams struct {
	Kind          string         `json:"kind"`
	Name          string         `json:"name"`
	Enabled       int64          `json:"enabled"`
	ConfigJson    string         `json:"config_json"`
	SecretRef     sql.NullString `json:"secret_ref"`
	RateLimitJson sql.NullString `json:"rate_limit_json"`
	NextRunAt     sql.NullInt64  `json:"next_run_at"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

func (q *Queries) CreateDiscoverySource(ctx context.Context, arg CreateDiscoverySourceParams) (DiscoverySource, error) {
	row := q.db.QueryRowContext(ctx, createDiscoverySource,
		arg.Kind,
		arg.Name,
		arg.Enabled,
		arg.ConfigJson,
		arg.SecretRef,
		arg.RateLimitJson,
		arg.NextRunAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DiscoverySource
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Enabled,
		&i.ConfigJson,
		&i.SecretRef,
		&i.RateLimitJson,
		&i.SchedulerState,
		&i.NextRunAt,
		&i.LockedUntil,
		&i.BackoffUntil,
		&i.FailureCount,
		&i.LastSuccessAt,
		&i.LastErrorKind,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDiscoverySource = `-- name: GetDiscoverySource :one
SELECT id, kind, name, enabled, config_json, secret_ref, rate_limit_json, scheduler_state, next_run_at, locked_until, backoff_until, failure_count, last_success_at, last_error_kind, last_error_message, created_at, updated_at FROM discovery_sources WHERE id = ?
`

type GetDiscoverySourceParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetDiscoverySource(ctx context.Context, arg GetDiscoverySourceParams) (DiscoverySource, error) {
	row := q.db.QueryRowContext(ctx, getDiscoverySource, arg.ID)
	var i DiscoverySource
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Enabled,
		&i.ConfigJson,
		&i.SecretRef,
		&i.RateLimitJson,
		&i.SchedulerState,
		&i.NextRunAt,
		&i.LockedUntil,
		&i.BackoffUntil,
		&i.FailureCount,
		&i.LastSuccessAt,
		&i.LastErrorKind,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const leaseDueDiscoverySources = `-- name: LeaseDueDiscoverySources :many
UPDATE discovery_sources
SET locked_until = ?, updated_at = ?
WHERE id IN (
  SELECT ds.id FROM discovery_sources AS ds
  WHERE ds.enabled = 1
    AND ds.scheduler_state IN ('healthy','backoff')
    AND (ds.next_run_at IS NULL OR ds.next_run_at <= ?)
    AND (ds.locked_until IS NULL OR ds.locked_until <= ?)
    AND (ds.backoff_until IS NULL OR ds.backoff_until <= ?)
  ORDER BY COALESCE(ds.next_run_at, 0), ds.id
  LIMIT ?
)
RETURNING id, kind, name, enabled, config_json, secret_ref, rate_limit_json, scheduler_state, next_run_at, locked_until, backoff_until, failure_count, last_success_at, last_error_kind, last_error_message, created_at, updated_at
`

type LeaseDueDiscoverySourcesParams struct {
	LockedUntil   sql.NullInt64 `json:"locked_until"`
	UpdatedAt     int64         `json:"updated_at"`
	NextRunAt     sql.NullInt64 `json:"next_run_at"`
	LockedUntil_2 sql.NullInt64 `json:"locked_until_2"`
	BackoffUntil  sql.NullInt64 `json:"backoff_until"`
	Limit         int64         `json:"limit"`
}

func (q *Queries) LeaseDueDiscoverySources(ctx context.Context, arg LeaseDueDiscoverySourcesParams) ([]DiscoverySource, error) {
	rows, err := q.db.QueryContext(ctx, leaseDueDiscoverySources,
		arg.LockedUntil,
		arg.UpdatedAt,
		arg.NextRunAt,
		arg.LockedUntil_2,
		arg.BackoffUntil,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoverySource
	for rows.Next() {
		var i DiscoverySource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Enabled,
			&i.ConfigJson,
			&i.SecretRef,
			&i.RateLimitJson,
			&i.SchedulerState,
			&i.NextRunAt,
			&i.LockedUntil,
			&i.BackoffUntil,
			&i.FailureCount,
			&i.LastSuccessAt,
			&i.LastErrorKind,
			&i.LastErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoverySources = `-- name: ListDiscoverySources :many
SELECT id, kind, name, enabled, config_json, secret_ref, rate_limit_json, scheduler_state, next_run_at, locked_until, backoff_until, failure_count, last_success_at, last_error_kind, last_error_message, created_at, updated_at FROM discovery_sources ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListDiscoverySourcesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListDiscoverySources(ctx context.Context, arg ListDiscoverySourcesParams) ([]DiscoverySource, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoverySources, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoverySource
	for rows.Next() {
		var i DiscoverySource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Enabled,
			&i.ConfigJson,
			&i.SecretRef,
			&i.RateLimitJson,
			&i.SchedulerState,
			&i.NextRunAt,
			&i.LockedUntil,
			&i.BackoffUntil,
			&i.FailureCount,
			&i.LastSuccessAt,
			&i.LastErrorKind,
			&i.LastErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiscoverySource = `-- name: UpdateDiscoverySource :one
UPDATE discovery_sources
SET name = ?, enabled = ?, config_json = ?, secret_ref = ?, rate_limit_json = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, kind, name, enabled, config_json, secret_ref, rate_limit_json, scheduler_state, next_run_at, locked_until, backoff_until, failure_count, last_success_at, last_error_kind, last_error_message, created_at, updated_at
`

type UpdateDiscoverySourceParams struct {
	Name          string         `json:"name"`
	Enabled       int64          `json:"enabled"`
	ConfigJson    string         `json:"config_json"`
	SecretRef     sql.NullString `json:"secret_ref"`
	RateLimitJson sql.NullString `json:"rate_limit_json"`
	UpdatedAt     int64          `json:"updated_at"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateDiscoverySource(ctx context.Context, arg UpdateDiscoverySourceParams) (DiscoverySource, error) {
	row := q.db.QueryRowContext(ctx, updateDiscoverySource,
		arg.Name,
		arg.Enabled,
		arg.ConfigJson,
		arg.SecretRef,
		arg.RateLimitJson,
		arg.UpdatedAt,
		arg.ID,
	)
	var i DiscoverySource
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Enabled,
		&i.ConfigJson,
		&i.SecretRef,
		&i.RateLimitJson,
		&i.SchedulerState,
		&i.NextRunAt,
		&i.LockedUntil,
		&i.BackoffUntil,
		&i.FailureCount,
		&i.LastSuccessAt,
		&i.LastErrorKind,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDiscoverySourceState = `-- name: UpdateDiscoverySourceState :exec
UPDATE discovery_sources
SET scheduler_state = ?, backoff_until = ?, failure_count = ?, last_error_kind = ?,
    last_error_message = ?, updated_at = ?
WHERE id = ?
`

type UpdateDiscoverySourceStateParams struct {
	SchedulerState   string         `json:"scheduler_state"`
	BackoffUntil     sql.NullInt64  `json:"backoff_until"`
	FailureCount     int64          `json:"failure_count"`
	LastErrorKind    sql.NullString `json:"last_error_kind"`
	LastErrorMessage sql.NullString `json:"last_error_message"`
	UpdatedAt        int64          `json:"updated_at"`
	ID               int64          `json:"id"`
}

func (q *Queries) UpdateDiscoverySourceState(ctx context.Context, arg UpdateDiscoverySourceStateParams) error {
	_, err := q.db.ExecContext(ctx, updateDiscoverySourceState,
		arg.SchedulerState,
		arg.BackoffUntil,
		arg.FailureCount,
		arg.LastErrorKind,
		arg.LastErrorMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
