// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discovery_tmdb.sql

package queries

import (
	"context"
	"database/sql"
)

const getTMDBMedia = `-- name: GetTMDBMedia :one
SELECT id, tmdb_id, media_type, language, title, original_title, release_year, poster_path, status, raw_json, fetched_at, next_refresh_at, last_error_kind, last_error_message FROM tmdb_media
WHERE tmdb_id = ? AND media_type = ? AND language = ?
`

type GetTMDBMediaParams struct {
	TmdbID    string `json:"tmdb_id"`
	MediaType string `json:"media_type"`
	Language  string `json:"language"`
}

func (q *Queries) GetTMDBMedia(ctx context.Context, arg GetTMDBMediaParams) (TmdbMedium, error) {
	row := q.db.QueryRowContext(ctx, getTMDBMedia, arg.TmdbID, arg.MediaType, arg.Language)
	var i TmdbMedium
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.MediaType,
		&i.Language,
		&i.Title,
		&i.OriginalTitle,
		&i.ReleaseYear,
		&i.PosterPath,
		&i.Status,
		&i.RawJson,
		&i.FetchedAt,
		&i.NextRefreshAt,
		&i.LastErrorKind,
		&i.LastErrorMessage,
	)
	return i, err
}

const searchTMDBMediaByTitle = `-- name: SearchTMDBMediaByTitle :many
SELECT id, tmdb_id, media_type, language, title, original_title, release_year, poster_path, status, raw_json, fetched_at, next_refresh_at, last_error_kind, last_error_message FROM tmdb_media
WHERE media_type = ? AND language = ? AND title LIKE ?
ORDER BY release_year DESC, fetched_at DESC
LIMIT ?
`

type SearchTMDBMediaByTitleParams struct {
	MediaType string `json:"media_type"`
	Language  string `json:"language"`
	Title     string `json:"title"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) SearchTMDBMediaByTitle(ctx context.Context, arg SearchTMDBMediaByTitleParams) ([]TmdbMedium, error) {
	rows, err := q.db.QueryContext(ctx, searchTMDBMediaByTitle,
		arg.MediaType,
		arg.Language,
		arg.Title,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TmdbMedium
	for rows.Next() {
		var i TmdbMedium
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.MediaType,
			&i.Language,
			&i.Title,
			&i.OriginalTitle,
			&i.ReleaseYear,
			&i.PosterPath,
			&i.Status,
			&i.RawJson,
			&i.FetchedAt,
			&i.NextRefreshAt,
			&i.LastErrorKind,
			&i.LastErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTMDBMedia = `-- name: UpsertTMDBMedia :one
INSERT INTO tmdb_media (
  tmdb_id, media_type, language, title, original_title, release_year,
  poster_path, status, raw_json, fetched_at, next_refresh_at,
  last_error_kind, last_error_message
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(tmdb_id, media_type, language) DO UPDATE SET
  title = excluded.title,
  original_title = excluded.original_title,
  release_year = excluded.release_year,
  poster_path = excluded.poster_path,
  status = excluded.status,
  raw_json = excluded.raw_json,
  fetched_at = excluded.fetched_at,
  next_refresh_at = excluded.next_refresh_at,
  last_error_kind = excluded.last_error_kind,
  last_error_message = excluded.last_error_message
RETURNING id, tmdb_id, media_type, language, title, original_title, release_year, poster_path, status, raw_json, fetched_at, next_refresh_at, last_error_kind, last_error_message
`

type UpsertTMDBMediaParams struct {
	TmdbID           string         `json:"tmdb_id"`
	MediaType        string         `json:"media_type"`
	Language         string         `json:"language"`
	Title            string         `json:"title"`
	OriginalTitle    sql.NullString `json:"original_title"`
	ReleaseYear      sql.NullInt64  `json:"release_year"`
	PosterPath       sql.NullString `json:"poster_path"`
	Status           sql.NullString `json:"status"`
	RawJson          string         `json:"raw_json"`
	FetchedAt        int64          `json:"fetched_at"`
	NextRefreshAt    int64          `json:"next_refresh_at"`
	LastErrorKind    sql.NullString `json:"last_error_kind"`
	LastErrorMessage sql.NullString `json:"last_error_message"`
}

func (q *Queries) UpsertTMDBMedia(ctx context.Context, arg UpsertTMDBMediaParams) (TmdbMedium, error) {
	row := q.db.QueryRowContext(ctx, upsertTMDBMedia,
		arg.TmdbID,
		arg.MediaType,
		arg.Language,
		arg.Title,
		arg.OriginalTitle,
		arg.ReleaseYear,
		arg.PosterPath,
		arg.Status,
		arg.RawJson,
		arg.FetchedAt,
		arg.NextRefreshAt,
		arg.LastErrorKind,
		arg.LastErrorMessage,
	)
	var i TmdbMedium
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.MediaType,
		&i.Language,
		&i.Title,
		&i.OriginalTitle,
		&i.ReleaseYear,
		&i.PosterPath,
		&i.Status,
		&i.RawJson,
		&i.FetchedAt,
		&i.NextRefreshAt,
		&i.LastErrorKind,
		&i.LastErrorMessage,
	)
	return i, err
}
