// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discovery_candidates.sql

package queries

import (
	"context"
	"database/sql"
)

const createSubscriptionMatch = `-- name: CreateSubscriptionMatch :one
INSERT INTO subscription_matches (
  subscription_id, resource_id, rule_profile_id, rule_profile_version,
  season_number, episode_start, episode_end, score_json, previous_score_json,
  decision, reason, dispatch_state, idempotency_key, created_at, updated_at, decided_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, subscription_id, resource_id, rule_profile_id, rule_profile_version, season_number, episode_start, episode_end, score_json, previous_score_json, decision, reason, dispatch_state, idempotency_key, queued_job_id, result_library_entry_id, result_blob_id, result_copy_id, failure_kind, failure_message, created_at, updated_at, decided_at, finished_at
`

type CreateSubscriptionMatchParams struct {
	SubscriptionID     int64          `json:"subscription_id"`
	ResourceID         int64          `json:"resource_id"`
	RuleProfileID      int64          `json:"rule_profile_id"`
	RuleProfileVersion int64          `json:"rule_profile_version"`
	SeasonNumber       sql.NullInt64  `json:"season_number"`
	EpisodeStart       sql.NullInt64  `json:"episode_start"`
	EpisodeEnd         sql.NullInt64  `json:"episode_end"`
	ScoreJson          string         `json:"score_json"`
	PreviousScoreJson  sql.NullString `json:"previous_score_json"`
	Decision           string         `json:"decision"`
	Reason             string         `json:"reason"`
	DispatchState      string         `json:"dispatch_state"`
	IdempotencyKey     string         `json:"idempotency_key"`
	CreatedAt          int64          `json:"created_at"`
	UpdatedAt          int64          `json:"updated_at"`
	DecidedAt          sql.NullInt64  `json:"decided_at"`
}

func (q *Queries) CreateSubscriptionMatch(ctx context.Context, arg CreateSubscriptionMatchParams) (SubscriptionMatch, error) {
	row := q.db.QueryRowContext(ctx, createSubscriptionMatch,
		arg.SubscriptionID,
		arg.ResourceID,
		arg.RuleProfileID,
		arg.RuleProfileVersion,
		arg.SeasonNumber,
		arg.EpisodeStart,
		arg.EpisodeEnd,
		arg.ScoreJson,
		arg.PreviousScoreJson,
		arg.Decision,
		arg.Reason,
		arg.DispatchState,
		arg.IdempotencyKey,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DecidedAt,
	)
	var i SubscriptionMatch
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.ResourceID,
		&i.RuleProfileID,
		&i.RuleProfileVersion,
		&i.SeasonNumber,
		&i.EpisodeStart,
		&i.EpisodeEnd,
		&i.ScoreJson,
		&i.PreviousScoreJson,
		&i.Decision,
		&i.Reason,
		&i.DispatchState,
		&i.IdempotencyKey,
		&i.QueuedJobID,
		&i.ResultLibraryEntryID,
		&i.ResultBlobID,
		&i.ResultCopyID,
		&i.FailureKind,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecidedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getDiscoveredResource = `-- name: GetDiscoveredResource :one
SELECT id, source_id, provider, link_kind, external_key, tmdb_id, media_type, title, season_number, episode_start, episode_end, share_code, receive_code, share_url_redacted, raw_text_redacted, raw_text_ref, parsed_json, feature_json, status, first_seen_at, last_seen_at FROM discovered_resources WHERE id = ?
`

type GetDiscoveredResourceParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetDiscoveredResource(ctx context.Context, arg GetDiscoveredResourceParams) (DiscoveredResource, error) {
	row := q.db.QueryRowContext(ctx, getDiscoveredResource, arg.ID)
	var i DiscoveredResource
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Provider,
		&i.LinkKind,
		&i.ExternalKey,
		&i.TmdbID,
		&i.MediaType,
		&i.Title,
		&i.SeasonNumber,
		&i.EpisodeStart,
		&i.EpisodeEnd,
		&i.ShareCode,
		&i.ReceiveCode,
		&i.ShareUrlRedacted,
		&i.RawTextRedacted,
		&i.RawTextRef,
		&i.ParsedJson,
		&i.FeatureJson,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getSubscriptionMatch = `-- name: GetSubscriptionMatch :one
SELECT id, subscription_id, resource_id, rule_profile_id, rule_profile_version, season_number, episode_start, episode_end, score_json, previous_score_json, decision, reason, dispatch_state, idempotency_key, queued_job_id, result_library_entry_id, result_blob_id, result_copy_id, failure_kind, failure_message, created_at, updated_at, decided_at, finished_at FROM subscription_matches WHERE id = ?
`

type GetSubscriptionMatchParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetSubscriptionMatch(ctx context.Context, arg GetSubscriptionMatchParams) (SubscriptionMatch, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionMatch, arg.ID)
	var i SubscriptionMatch
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.ResourceID,
		&i.RuleProfileID,
		&i.RuleProfileVersion,
		&i.SeasonNumber,
		&i.EpisodeStart,
		&i.EpisodeEnd,
		&i.ScoreJson,
		&i.PreviousScoreJson,
		&i.Decision,
		&i.Reason,
		&i.DispatchState,
		&i.IdempotencyKey,
		&i.QueuedJobID,
		&i.ResultLibraryEntryID,
		&i.ResultBlobID,
		&i.ResultCopyID,
		&i.FailureKind,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecidedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getSubscriptionMatchByIdempotencyKey = `-- name: GetSubscriptionMatchByIdempotencyKey :one
SELECT id, subscription_id, resource_id, rule_profile_id, rule_profile_version, season_number, episode_start, episode_end, score_json, previous_score_json, decision, reason, dispatch_state, idempotency_key, queued_job_id, result_library_entry_id, result_blob_id, result_copy_id, failure_kind, failure_message, created_at, updated_at, decided_at, finished_at FROM subscription_matches WHERE idempotency_key = ?
`

type GetSubscriptionMatchByIdempotencyKeyParams struct {
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetSubscriptionMatchByIdempotencyKey(ctx context.Context, arg GetSubscriptionMatchByIdempotencyKeyParams) (SubscriptionMatch, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionMatchByIdempotencyKey, arg.IdempotencyKey)
	var i SubscriptionMatch
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.ResourceID,
		&i.RuleProfileID,
		&i.RuleProfileVersion,
		&i.SeasonNumber,
		&i.EpisodeStart,
		&i.EpisodeEnd,
		&i.ScoreJson,
		&i.PreviousScoreJson,
		&i.Decision,
		&i.Reason,
		&i.DispatchState,
		&i.IdempotencyKey,
		&i.QueuedJobID,
		&i.ResultLibraryEntryID,
		&i.ResultBlobID,
		&i.ResultCopyID,
		&i.FailureKind,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecidedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listDiscoveredResources = `-- name: ListDiscoveredResources :many
SELECT id, source_id, provider, link_kind, external_key, tmdb_id, media_type, title, season_number, episode_start, episode_end, share_code, receive_code, share_url_redacted, raw_text_redacted, raw_text_ref, parsed_json, feature_json, status, first_seen_at, last_seen_at FROM discovered_resources ORDER BY last_seen_at DESC LIMIT ? OFFSET ?
`

type ListDiscoveredResourcesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListDiscoveredResources(ctx context.Context, arg ListDiscoveredResourcesParams) ([]DiscoveredResource, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoveredResources, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveredResource
	for rows.Next() {
		var i DiscoveredResource
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Provider,
			&i.LinkKind,
			&i.ExternalKey,
			&i.TmdbID,
			&i.MediaType,
			&i.Title,
			&i.SeasonNumber,
			&i.EpisodeStart,
			&i.EpisodeEnd,
			&i.ShareCode,
			&i.ReceiveCode,
			&i.ShareUrlRedacted,
			&i.RawTextRedacted,
			&i.RawTextRef,
			&i.ParsedJson,
			&i.FeatureJson,
			&i.Status,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscriptionMatchDispatch = `-- name: UpdateSubscriptionMatchDispatch :exec
UPDATE subscription_matches
SET decision = ?, dispatch_state = ?, queued_job_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateSubscriptionMatchDispatchParams struct {
	Decision      string        `json:"decision"`
	DispatchState string        `json:"dispatch_state"`
	QueuedJobID   sql.NullInt64 `json:"queued_job_id"`
	UpdatedAt     int64         `json:"updated_at"`
	ID            int64         `json:"id"`
}

func (q *Queries) UpdateSubscriptionMatchDispatch(ctx context.Context, arg UpdateSubscriptionMatchDispatchParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionMatchDispatch,
		arg.Decision,
		arg.DispatchState,
		arg.QueuedJobID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateSubscriptionMatchResult = `-- name: UpdateSubscriptionMatchResult :exec
UPDATE subscription_matches
SET decision = ?, dispatch_state = ?, result_library_entry_id = ?, result_blob_id = ?,
    result_copy_id = ?, failure_kind = ?, failure_message = ?, updated_at = ?,
    finished_at = ?
WHERE id = ?
`

type UpdateSubscriptionMatchResultParams struct {
	Decision             string         `json:"decision"`
	DispatchState        string         `json:"dispatch_state"`
	ResultLibraryEntryID sql.NullInt64  `json:"result_library_entry_id"`
	ResultBlobID         sql.NullInt64  `json:"result_blob_id"`
	ResultCopyID         sql.NullInt64  `json:"result_copy_id"`
	FailureKind          sql.NullString `json:"failure_kind"`
	FailureMessage       sql.NullString `json:"failure_message"`
	UpdatedAt            int64          `json:"updated_at"`
	FinishedAt           sql.NullInt64  `json:"finished_at"`
	ID                   int64          `json:"id"`
}

func (q *Queries) UpdateSubscriptionMatchResult(ctx context.Context, arg UpdateSubscriptionMatchResultParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscriptionMatchResult,
		arg.Decision,
		arg.DispatchState,
		arg.ResultLibraryEntryID,
		arg.ResultBlobID,
		arg.ResultCopyID,
		arg.FailureKind,
		arg.FailureMessage,
		arg.UpdatedAt,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const upsertDiscoveredResource = `-- name: UpsertDiscoveredResource :one
INSERT INTO discovered_resources (
  source_id, provider, link_kind, external_key, tmdb_id, media_type, title,
  season_number, episode_start, episode_end, share_code, receive_code,
  share_url_redacted, raw_text_redacted, raw_text_ref, parsed_json,
  feature_json, status, first_seen_at, last_seen_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(source_id, external_key) DO UPDATE SET
  tmdb_id = excluded.tmdb_id,
  media_type = excluded.media_type,
  title = excluded.title,
  season_number = excluded.season_number,
  episode_start = excluded.episode_start,
  episode_end = excluded.episode_end,
  share_code = excluded.share_code,
  receive_code = excluded.receive_code,
  share_url_redacted = excluded.share_url_redacted,
  raw_text_redacted = excluded.raw_text_redacted,
  raw_text_ref = excluded.raw_text_ref,
  parsed_json = excluded.parsed_json,
  feature_json = excluded.feature_json,
  last_seen_at = excluded.last_seen_at
RETURNING id, source_id, provider, link_kind, external_key, tmdb_id, media_type, title, season_number, episode_start, episode_end, share_code, receive_code, share_url_redacted, raw_text_redacted, raw_text_ref, parsed_json, feature_json, status, first_seen_at, last_seen_at
`

type UpsertDiscoveredResourceParams struct {
	SourceID         int64          `json:"source_id"`
	Provider         string         `json:"provider"`
	LinkKind         string         `json:"link_kind"`
	ExternalKey      string         `json:"external_key"`
	TmdbID           sql.NullString `json:"tmdb_id"`
	MediaType        sql.NullString `json:"media_type"`
	Title            sql.NullString `json:"title"`
	SeasonNumber     sql.NullInt64  `json:"season_number"`
	EpisodeStart     sql.NullInt64  `json:"episode_start"`
	EpisodeEnd       sql.NullInt64  `json:"episode_end"`
	ShareCode        sql.NullString `json:"share_code"`
	ReceiveCode      sql.NullString `json:"receive_code"`
	ShareUrlRedacted sql.NullString `json:"share_url_redacted"`
	RawTextRedacted  sql.NullString `json:"raw_text_redacted"`
	RawTextRef       sql.NullString `json:"raw_text_ref"`
	ParsedJson       string         `json:"parsed_json"`
	FeatureJson      string         `json:"feature_json"`
	Status           string         `json:"status"`
	FirstSeenAt      int64          `json:"first_seen_at"`
	LastSeenAt       int64          `json:"last_seen_at"`
}

func (q *Queries) UpsertDiscoveredResource(ctx context.Context, arg UpsertDiscoveredResourceParams) (DiscoveredResource, error) {
	row := q.db.QueryRowContext(ctx, upsertDiscoveredResource,
		arg.SourceID,
		arg.Provider,
		arg.LinkKind,
		arg.ExternalKey,
		arg.TmdbID,
		arg.MediaType,
		arg.Title,
		arg.SeasonNumber,
		arg.EpisodeStart,
		arg.EpisodeEnd,
		arg.ShareCode,
		arg.ReceiveCode,
		arg.ShareUrlRedacted,
		arg.RawTextRedacted,
		arg.RawTextRef,
		arg.ParsedJson,
		arg.FeatureJson,
		arg.Status,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	var i DiscoveredResource
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Provider,
		&i.LinkKind,
		&i.ExternalKey,
		&i.TmdbID,
		&i.MediaType,
		&i.Title,
		&i.SeasonNumber,
		&i.EpisodeStart,
		&i.EpisodeEnd,
		&i.ShareCode,
		&i.ReceiveCode,
		&i.ShareUrlRedacted,
		&i.RawTextRedacted,
		&i.RawTextRef,
		&i.ParsedJson,
		&i.FeatureJson,
		&i.Status,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}
