// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discovery_orchestrator.sql

package queries

import (
	"context"
	"database/sql"
)

const getDiscoverySubscriptionBundle = `-- name: GetDiscoverySubscriptionBundle :one
SELECT
  s.id AS subscription_id,
  s.tmdb_id,
  s.media_type,
  s.library_id,
  s.producer_profile_id,
  s.rule_profile_id,
  s.match_mode,
  rp.version AS rule_profile_version,
  rp.rules_json AS rule_profile_json
FROM discovery_subscriptions s
JOIN rule_profiles rp ON rp.id = s.rule_profile_id
WHERE s.id = ?
`

type GetDiscoverySubscriptionBundleParams struct {
	ID int64 `json:"id"`
}

type GetDiscoverySubscriptionBundleRow struct {
	SubscriptionID     int64  `json:"subscription_id"`
	TmdbID             string `json:"tmdb_id"`
	MediaType          string `json:"media_type"`
	LibraryID          int64  `json:"library_id"`
	ProducerProfileID  int64  `json:"producer_profile_id"`
	RuleProfileID      int64  `json:"rule_profile_id"`
	MatchMode          string `json:"match_mode"`
	RuleProfileVersion int64  `json:"rule_profile_version"`
	RuleProfileJson    string `json:"rule_profile_json"`
}

func (q *Queries) GetDiscoverySubscriptionBundle(ctx context.Context, arg GetDiscoverySubscriptionBundleParams) (GetDiscoverySubscriptionBundleRow, error) {
	row := q.db.QueryRowContext(ctx, getDiscoverySubscriptionBundle, arg.ID)
	var i GetDiscoverySubscriptionBundleRow
	err := row.Scan(
		&i.SubscriptionID,
		&i.TmdbID,
		&i.MediaType,
		&i.LibraryID,
		&i.ProducerProfileID,
		&i.RuleProfileID,
		&i.MatchMode,
		&i.RuleProfileVersion,
		&i.RuleProfileJson,
	)
	return i, err
}

const linkSubscriptionMatchDispatchJobIfClaimable = `-- name: LinkSubscriptionMatchDispatchJobIfClaimable :one
UPDATE subscription_matches
SET decision = 'queue',
    dispatch_state = 'queued',
    queued_job_id = ?,
    updated_at = ?,
    decided_at = COALESCE(decided_at, ?),
    failure_kind = NULL,
    failure_message = NULL
WHERE subscription_matches.id = ?
  AND subscription_matches.dispatch_state IN ('none','failed')
  AND subscription_matches.decision IN ('accept','queue')
  AND EXISTS (
    SELECT 1
    FROM discovered_resources r
    WHERE r.id = subscription_matches.resource_id
      AND r.provider = '115'
      AND r.link_kind = '115_share'
      AND r.status NOT IN ('rejected','unsupported_provider')
  )
RETURNING id, subscription_id, resource_id, rule_profile_id, rule_profile_version, season_number, episode_start, episode_end, score_json, previous_score_json, decision, reason, dispatch_state, idempotency_key, queued_job_id, result_library_entry_id, result_blob_id, result_copy_id, failure_kind, failure_message, created_at, updated_at, decided_at, finished_at
`

type LinkSubscriptionMatchDispatchJobIfClaimableParams struct {
	QueuedJobID sql.NullInt64 `json:"queued_job_id"`
	UpdatedAt   int64         `json:"updated_at"`
	DecidedAt   sql.NullInt64 `json:"decided_at"`
	ID          int64         `json:"id"`
}

func (q *Queries) LinkSubscriptionMatchDispatchJobIfClaimable(ctx context.Context, arg LinkSubscriptionMatchDispatchJobIfClaimableParams) (SubscriptionMatch, error) {
	row := q.db.QueryRowContext(ctx, linkSubscriptionMatchDispatchJobIfClaimable,
		arg.QueuedJobID,
		arg.UpdatedAt,
		arg.DecidedAt,
		arg.ID,
	)
	var i SubscriptionMatch
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.ResourceID,
		&i.RuleProfileID,
		&i.RuleProfileVersion,
		&i.SeasonNumber,
		&i.EpisodeStart,
		&i.EpisodeEnd,
		&i.ScoreJson,
		&i.PreviousScoreJson,
		&i.Decision,
		&i.Reason,
		&i.DispatchState,
		&i.IdempotencyKey,
		&i.QueuedJobID,
		&i.ResultLibraryEntryID,
		&i.ResultBlobID,
		&i.ResultCopyID,
		&i.FailureKind,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DecidedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listCandidateResourcesForSubscription = `-- name: ListCandidateResourcesForSubscription :many
SELECT
  id, provider, link_kind, tmdb_id, media_type, title, season_number,
  episode_start, episode_end, share_code, receive_code, share_url_redacted,
  feature_json
FROM discovered_resources
WHERE tmdb_id = ? AND media_type = ? AND status IN ('candidate','review','accepted','failed')
ORDER BY last_seen_at DESC
LIMIT ?
`

type ListCandidateResourcesForSubscriptionParams struct {
	TmdbID    sql.NullString `json:"tmdb_id"`
	MediaType sql.NullString `json:"media_type"`
	Limit     int64          `json:"limit"`
}

type ListCandidateResourcesForSubscriptionRow struct {
	ID               int64          `json:"id"`
	Provider         string         `json:"provider"`
	LinkKind         string         `json:"link_kind"`
	TmdbID           sql.NullString `json:"tmdb_id"`
	MediaType        sql.NullString `json:"media_type"`
	Title            sql.NullString `json:"title"`
	SeasonNumber     sql.NullInt64  `json:"season_number"`
	EpisodeStart     sql.NullInt64  `json:"episode_start"`
	EpisodeEnd       sql.NullInt64  `json:"episode_end"`
	ShareCode        sql.NullString `json:"share_code"`
	ReceiveCode      sql.NullString `json:"receive_code"`
	ShareUrlRedacted sql.NullString `json:"share_url_redacted"`
	FeatureJson      string         `json:"feature_json"`
}

func (q *Queries) ListCandidateResourcesForSubscription(ctx context.Context, arg ListCandidateResourcesForSubscriptionParams) ([]ListCandidateResourcesForSubscriptionRow, error) {
	rows, err := q.db.QueryContext(ctx, listCandidateResourcesForSubscription, arg.TmdbID, arg.MediaType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCandidateResourcesForSubscriptionRow
	for rows.Next() {
		var i ListCandidateResourcesForSubscriptionRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.LinkKind,
			&i.TmdbID,
			&i.MediaType,
			&i.Title,
			&i.SeasonNumber,
			&i.EpisodeStart,
			&i.EpisodeEnd,
			&i.ShareCode,
			&i.ReceiveCode,
			&i.ShareUrlRedacted,
			&i.FeatureJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadDispatchBundle = `-- name: LoadDispatchBundle :one
SELECT
  m.id AS match_id,
  m.subscription_id,
  r.id AS resource_id,
  s.library_id,
  p.provider,
  p.tool,
  p.target_account,
  p.target_subdir_template,
  p.library_rel_path_template,
  p.default_args_json,
  r.share_url_redacted,
  r.share_code,
  r.receive_code,
  r.title,
  r.provider AS resource_provider,
  r.link_kind AS resource_link_kind,
  r.status AS resource_status
FROM subscription_matches m
JOIN discovery_subscriptions s ON s.id = m.subscription_id
JOIN discovery_producer_profiles p ON p.id = s.producer_profile_id
JOIN discovered_resources r ON r.id = m.resource_id
WHERE m.id = ?
  AND m.decision IN ('accept','queue')
  AND r.provider = '115'
  AND r.link_kind = '115_share'
  AND r.status NOT IN ('rejected','unsupported_provider')
`

type LoadDispatchBundleParams struct {
	ID int64 `json:"id"`
}

type LoadDispatchBundleRow struct {
	MatchID                int64          `json:"match_id"`
	SubscriptionID         int64          `json:"subscription_id"`
	ResourceID             int64          `json:"resource_id"`
	LibraryID              int64          `json:"library_id"`
	Provider               string         `json:"provider"`
	Tool                   string         `json:"tool"`
	TargetAccount          string         `json:"target_account"`
	TargetSubdirTemplate   string         `json:"target_subdir_template"`
	LibraryRelPathTemplate string         `json:"library_rel_path_template"`
	DefaultArgsJson        string         `json:"default_args_json"`
	ShareUrlRedacted       sql.NullString `json:"share_url_redacted"`
	ShareCode              sql.NullString `json:"share_code"`
	ReceiveCode            sql.NullString `json:"receive_code"`
	Title                  sql.NullString `json:"title"`
	ResourceProvider       string         `json:"resource_provider"`
	ResourceLinkKind       string         `json:"resource_link_kind"`
	ResourceStatus         string         `json:"resource_status"`
}

func (q *Queries) LoadDispatchBundle(ctx context.Context, arg LoadDispatchBundleParams) (LoadDispatchBundleRow, error) {
	row := q.db.QueryRowContext(ctx, loadDispatchBundle, arg.ID)
	var i LoadDispatchBundleRow
	err := row.Scan(
		&i.MatchID,
		&i.SubscriptionID,
		&i.ResourceID,
		&i.LibraryID,
		&i.Provider,
		&i.Tool,
		&i.TargetAccount,
		&i.TargetSubdirTemplate,
		&i.LibraryRelPathTemplate,
		&i.DefaultArgsJson,
		&i.ShareUrlRedacted,
		&i.ShareCode,
		&i.ReceiveCode,
		&i.Title,
		&i.ResourceProvider,
		&i.ResourceLinkKind,
		&i.ResourceStatus,
	)
	return i, err
}

const loadReconcileBundle = `-- name: LoadReconcileBundle :one
SELECT
  m.id AS match_id,
  j.id AS job_id,
  j.status AS job_status,
  COALESCE(j.progress, '{}') AS job_progress_json,
  COALESCE(j.error, '') AS job_error
FROM subscription_matches m
JOIN jobs j ON j.id = m.queued_job_id
WHERE m.id = ? AND j.id = ?
`

type LoadReconcileBundleParams struct {
	ID   int64 `json:"id"`
	ID_2 int64 `json:"id_2"`
}

type LoadReconcileBundleRow struct {
	MatchID         int64  `json:"match_id"`
	JobID           int64  `json:"job_id"`
	JobStatus       string `json:"job_status"`
	JobProgressJson string `json:"job_progress_json"`
	JobError        string `json:"job_error"`
}

func (q *Queries) LoadReconcileBundle(ctx context.Context, arg LoadReconcileBundleParams) (LoadReconcileBundleRow, error) {
	row := q.db.QueryRowContext(ctx, loadReconcileBundle, arg.ID, arg.ID_2)
	var i LoadReconcileBundleRow
	err := row.Scan(
		&i.MatchID,
		&i.JobID,
		&i.JobStatus,
		&i.JobProgressJson,
		&i.JobError,
	)
	return i, err
}

const updateTelegramChannelCursorByRef = `-- name: UpdateTelegramChannelCursorByRef :exec
UPDATE telegram_channels
SET last_message_id = ?, last_message_date = ?, failure_count = 0,
    last_error_kind = NULL, last_error_message = NULL, locked_until = NULL,
    updated_at = ?
WHERE source_id = ? AND channel_ref = ?
`

type UpdateTelegramChannelCursorByRefParams struct {
	LastMessageID   sql.NullInt64 `json:"last_message_id"`
	LastMessageDate sql.NullInt64 `json:"last_message_date"`
	UpdatedAt       int64         `json:"updated_at"`
	SourceID        int64         `json:"source_id"`
	ChannelRef      string        `json:"channel_ref"`
}

func (q *Queries) UpdateTelegramChannelCursorByRef(ctx context.Context, arg UpdateTelegramChannelCursorByRefParams) error {
	_, err := q.db.ExecContext(ctx, updateTelegramChannelCursorByRef,
		arg.LastMessageID,
		arg.LastMessageDate,
		arg.UpdatedAt,
		arg.SourceID,
		arg.ChannelRef,
	)
	return err
}
