// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discovery_admin.sql

package queries

import (
	"context"
	"database/sql"
)

const getDiscoveryRawResourceForDebug = `-- name: GetDiscoveryRawResourceForDebug :one
SELECT id, raw_text_redacted, raw_text_ref
FROM discovered_resources
WHERE id = ?
`

type GetDiscoveryRawResourceForDebugParams struct {
	ID int64 `json:"id"`
}

type GetDiscoveryRawResourceForDebugRow struct {
	ID              int64          `json:"id"`
	RawTextRedacted sql.NullString `json:"raw_text_redacted"`
	RawTextRef      sql.NullString `json:"raw_text_ref"`
}

func (q *Queries) GetDiscoveryRawResourceForDebug(ctx context.Context, arg GetDiscoveryRawResourceForDebugParams) (GetDiscoveryRawResourceForDebugRow, error) {
	row := q.db.QueryRowContext(ctx, getDiscoveryRawResourceForDebug, arg.ID)
	var i GetDiscoveryRawResourceForDebugRow
	err := row.Scan(&i.ID, &i.RawTextRedacted, &i.RawTextRef)
	return i, err
}

const listDiscoveredResourcesRedacted = `-- name: ListDiscoveredResourcesRedacted :many
SELECT
  id, source_id, provider, link_kind, external_key, tmdb_id, media_type, title,
  season_number, episode_start, episode_end, share_url_redacted,
  raw_text_redacted, parsed_json, feature_json, status, first_seen_at, last_seen_at
FROM discovered_resources
ORDER BY last_seen_at DESC
LIMIT ? OFFSET ?
`

type ListDiscoveredResourcesRedactedParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListDiscoveredResourcesRedactedRow struct {
	ID               int64          `json:"id"`
	SourceID         int64          `json:"source_id"`
	Provider         string         `json:"provider"`
	LinkKind         string         `json:"link_kind"`
	ExternalKey      string         `json:"external_key"`
	TmdbID           sql.NullString `json:"tmdb_id"`
	MediaType        sql.NullString `json:"media_type"`
	Title            sql.NullString `json:"title"`
	SeasonNumber     sql.NullInt64  `json:"season_number"`
	EpisodeStart     sql.NullInt64  `json:"episode_start"`
	EpisodeEnd       sql.NullInt64  `json:"episode_end"`
	ShareUrlRedacted sql.NullString `json:"share_url_redacted"`
	RawTextRedacted  sql.NullString `json:"raw_text_redacted"`
	ParsedJson       string         `json:"parsed_json"`
	FeatureJson      string         `json:"feature_json"`
	Status           string         `json:"status"`
	FirstSeenAt      int64          `json:"first_seen_at"`
	LastSeenAt       int64          `json:"last_seen_at"`
}

func (q *Queries) ListDiscoveredResourcesRedacted(ctx context.Context, arg ListDiscoveredResourcesRedactedParams) ([]ListDiscoveredResourcesRedactedRow, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoveredResourcesRedacted, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDiscoveredResourcesRedactedRow
	for rows.Next() {
		var i ListDiscoveredResourcesRedactedRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Provider,
			&i.LinkKind,
			&i.ExternalKey,
			&i.TmdbID,
			&i.MediaType,
			&i.Title,
			&i.SeasonNumber,
			&i.EpisodeStart,
			&i.EpisodeEnd,
			&i.ShareUrlRedacted,
			&i.RawTextRedacted,
			&i.ParsedJson,
			&i.FeatureJson,
			&i.Status,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionMatchesForAdmin = `-- name: ListSubscriptionMatchesForAdmin :many
SELECT id, subscription_id, resource_id, rule_profile_id, rule_profile_version, season_number, episode_start, episode_end, score_json, previous_score_json, decision, reason, dispatch_state, idempotency_key, queued_job_id, result_library_entry_id, result_blob_id, result_copy_id, failure_kind, failure_message, created_at, updated_at, decided_at, finished_at
FROM subscription_matches
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type ListSubscriptionMatchesForAdminParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListSubscriptionMatchesForAdmin(ctx context.Context, arg ListSubscriptionMatchesForAdminParams) ([]SubscriptionMatch, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionMatchesForAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionMatch
	for rows.Next() {
		var i SubscriptionMatch
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.ResourceID,
			&i.RuleProfileID,
			&i.RuleProfileVersion,
			&i.SeasonNumber,
			&i.EpisodeStart,
			&i.EpisodeEnd,
			&i.ScoreJson,
			&i.PreviousScoreJson,
			&i.Decision,
			&i.Reason,
			&i.DispatchState,
			&i.IdempotencyKey,
			&i.QueuedJobID,
			&i.ResultLibraryEntryID,
			&i.ResultBlobID,
			&i.ResultCopyID,
			&i.FailureKind,
			&i.FailureMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DecidedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
