// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discovery_runs.sql

package queries

import (
	"context"
	"database/sql"
)

const createDiscoveryRawAccessEvent = `-- name: CreateDiscoveryRawAccessEvent :exec
INSERT INTO discovery_raw_access_events (
  resource_id, actor_user_id, request_id, response_bytes, redacted, accessed_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateDiscoveryRawAccessEventParams struct {
	ResourceID    int64          `json:"resource_id"`
	ActorUserID   string         `json:"actor_user_id"`
	RequestID     sql.NullString `json:"request_id"`
	ResponseBytes int64          `json:"response_bytes"`
	Redacted      int64          `json:"redacted"`
	AccessedAt    int64          `json:"accessed_at"`
}

func (q *Queries) CreateDiscoveryRawAccessEvent(ctx context.Context, arg CreateDiscoveryRawAccessEventParams) error {
	_, err := q.db.ExecContext(ctx, createDiscoveryRawAccessEvent,
		arg.ResourceID,
		arg.ActorUserID,
		arg.RequestID,
		arg.ResponseBytes,
		arg.Redacted,
		arg.AccessedAt,
	)
	return err
}

const createDiscoveryRun = `-- name: CreateDiscoveryRun :one
INSERT INTO discovery_runs (
  kind, source_id, subscription_id, job_id, status, counters_json, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, kind, source_id, subscription_id, job_id, status, counters_json, error_kind, error_message, started_at, finished_at, created_at
`

type CreateDiscoveryRunParams struct {
	Kind           string        `json:"kind"`
	SourceID       sql.NullInt64 `json:"source_id"`
	SubscriptionID sql.NullInt64 `json:"subscription_id"`
	JobID          sql.NullInt64 `json:"job_id"`
	Status         string        `json:"status"`
	CountersJson   string        `json:"counters_json"`
	CreatedAt      int64         `json:"created_at"`
}

func (q *Queries) CreateDiscoveryRun(ctx context.Context, arg CreateDiscoveryRunParams) (DiscoveryRun, error) {
	row := q.db.QueryRowContext(ctx, createDiscoveryRun,
		arg.Kind,
		arg.SourceID,
		arg.SubscriptionID,
		arg.JobID,
		arg.Status,
		arg.CountersJson,
		arg.CreatedAt,
	)
	var i DiscoveryRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SourceID,
		&i.SubscriptionID,
		&i.JobID,
		&i.Status,
		&i.CountersJson,
		&i.ErrorKind,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const finishDiscoveryRun = `-- name: FinishDiscoveryRun :exec
UPDATE discovery_runs
SET status = ?, counters_json = ?, error_kind = ?, error_message = ?,
    started_at = COALESCE(started_at, ?), finished_at = ?
WHERE id = ?
`

type FinishDiscoveryRunParams struct {
	Status       string         `json:"status"`
	CountersJson string         `json:"counters_json"`
	ErrorKind    sql.NullString `json:"error_kind"`
	ErrorMessage sql.NullString `json:"error_message"`
	StartedAt    sql.NullInt64  `json:"started_at"`
	FinishedAt   sql.NullInt64  `json:"finished_at"`
	ID           int64          `json:"id"`
}

func (q *Queries) FinishDiscoveryRun(ctx context.Context, arg FinishDiscoveryRunParams) error {
	_, err := q.db.ExecContext(ctx, finishDiscoveryRun,
		arg.Status,
		arg.CountersJson,
		arg.ErrorKind,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const listDiscoveryRuns = `-- name: ListDiscoveryRuns :many
SELECT id, kind, source_id, subscription_id, job_id, status, counters_json, error_kind, error_message, started_at, finished_at, created_at FROM discovery_runs ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListDiscoveryRunsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListDiscoveryRuns(ctx context.Context, arg ListDiscoveryRunsParams) ([]DiscoveryRun, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoveryRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryRun
	for rows.Next() {
		var i DiscoveryRun
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.SourceID,
			&i.SubscriptionID,
			&i.JobID,
			&i.Status,
			&i.CountersJson,
			&i.ErrorKind,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
