// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: emby_management.sql

package queries

import (
	"context"
	"database/sql"
)

const listEmbyLibraryMappings = `-- name: ListEmbyLibraryMappings :many
SELECT id, emby_server_id, emby_path_prefix, emby_path_prefix_norm, library_id, echo_rel_prefix, case_sensitive, enabled, created_at, updated_at
FROM emby_library_mappings
ORDER BY emby_server_id, length(emby_path_prefix) DESC, id
LIMIT ? OFFSET ?
`

type ListEmbyLibraryMappingsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListEmbyLibraryMappingsRow struct {
	ID                 int64  `json:"id"`
	EmbyServerID       string `json:"emby_server_id"`
	EmbyPathPrefix     string `json:"emby_path_prefix"`
	EmbyPathPrefixNorm string `json:"emby_path_prefix_norm"`
	LibraryID          int64  `json:"library_id"`
	EchoRelPrefix      string `json:"echo_rel_prefix"`
	CaseSensitive      int64  `json:"case_sensitive"`
	Enabled            int64  `json:"enabled"`
	CreatedAt          int64  `json:"created_at"`
	UpdatedAt          int64  `json:"updated_at"`
}

func (q *Queries) ListEmbyLibraryMappings(ctx context.Context, arg ListEmbyLibraryMappingsParams) ([]ListEmbyLibraryMappingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmbyLibraryMappings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmbyLibraryMappingsRow
	for rows.Next() {
		var i ListEmbyLibraryMappingsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmbyServerID,
			&i.EmbyPathPrefix,
			&i.EmbyPathPrefixNorm,
			&i.LibraryID,
			&i.EchoRelPrefix,
			&i.CaseSensitive,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmbyServers = `-- name: ListEmbyServers :many
SELECT id, name, base_url, public_base_url, proxy_prefix, enabled, created_at, updated_at
FROM emby_servers
ORDER BY id
LIMIT ? OFFSET ?
`

type ListEmbyServersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListEmbyServersRow struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	BaseUrl       string `json:"base_url"`
	PublicBaseUrl string `json:"public_base_url"`
	ProxyPrefix   string `json:"proxy_prefix"`
	Enabled       int64  `json:"enabled"`
	CreatedAt     int64  `json:"created_at"`
	UpdatedAt     int64  `json:"updated_at"`
}

func (q *Queries) ListEmbyServers(ctx context.Context, arg ListEmbyServersParams) ([]ListEmbyServersRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmbyServers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmbyServersRow
	for rows.Next() {
		var i ListEmbyServersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.PublicBaseUrl,
			&i.ProxyPrefix,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmbyUserLinks = `-- name: ListEmbyUserLinks :many
SELECT id, emby_server_id, emby_user_id, echo_user_id, enabled, created_at, updated_at
FROM emby_user_links
ORDER BY emby_server_id, emby_user_id
LIMIT ? OFFSET ?
`

type ListEmbyUserLinksParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListEmbyUserLinksRow struct {
	ID           int64  `json:"id"`
	EmbyServerID string `json:"emby_server_id"`
	EmbyUserID   string `json:"emby_user_id"`
	EchoUserID   string `json:"echo_user_id"`
	Enabled      int64  `json:"enabled"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) ListEmbyUserLinks(ctx context.Context, arg ListEmbyUserLinksParams) ([]ListEmbyUserLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmbyUserLinks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmbyUserLinksRow
	for rows.Next() {
		var i ListEmbyUserLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.EmbyServerID,
			&i.EmbyUserID,
			&i.EchoUserID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmbyLibraryMapping = `-- name: UpdateEmbyLibraryMapping :one
UPDATE emby_library_mappings
SET
  emby_path_prefix = ?,
  emby_path_prefix_norm = ?,
  library_id = ?,
  echo_rel_prefix = ?,
  case_sensitive = ?,
  enabled = ?,
  updated_at = ?
WHERE id = ?
RETURNING id, emby_server_id, library_id, emby_path_prefix, emby_path_prefix_norm, echo_rel_prefix, case_sensitive, enabled, created_at, updated_at
`

type UpdateEmbyLibraryMappingParams struct {
	EmbyPathPrefix     string `json:"emby_path_prefix"`
	EmbyPathPrefixNorm string `json:"emby_path_prefix_norm"`
	LibraryID          int64  `json:"library_id"`
	EchoRelPrefix      string `json:"echo_rel_prefix"`
	CaseSensitive      int64  `json:"case_sensitive"`
	Enabled            int64  `json:"enabled"`
	UpdatedAt          int64  `json:"updated_at"`
	ID                 int64  `json:"id"`
}

func (q *Queries) UpdateEmbyLibraryMapping(ctx context.Context, arg UpdateEmbyLibraryMappingParams) (EmbyLibraryMapping, error) {
	row := q.db.QueryRowContext(ctx, updateEmbyLibraryMapping,
		arg.EmbyPathPrefix,
		arg.EmbyPathPrefixNorm,
		arg.LibraryID,
		arg.EchoRelPrefix,
		arg.CaseSensitive,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	var i EmbyLibraryMapping
	err := row.Scan(
		&i.ID,
		&i.EmbyServerID,
		&i.LibraryID,
		&i.EmbyPathPrefix,
		&i.EmbyPathPrefixNorm,
		&i.EchoRelPrefix,
		&i.CaseSensitive,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEmbyServer = `-- name: UpsertEmbyServer :one
INSERT INTO emby_servers (
  id, name, base_url, api_key_ref, public_base_url, proxy_prefix, enabled, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  base_url = excluded.base_url,
  api_key_ref = excluded.api_key_ref,
  public_base_url = excluded.public_base_url,
  proxy_prefix = excluded.proxy_prefix,
  enabled = excluded.enabled,
  updated_at = excluded.updated_at
RETURNING id, name, base_url, public_base_url, proxy_prefix, enabled, created_at, updated_at
`

type UpsertEmbyServerParams struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	BaseUrl       string         `json:"base_url"`
	ApiKeyRef     sql.NullString `json:"api_key_ref"`
	PublicBaseUrl string         `json:"public_base_url"`
	ProxyPrefix   string         `json:"proxy_prefix"`
	Enabled       int64          `json:"enabled"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

type UpsertEmbyServerRow struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	BaseUrl       string `json:"base_url"`
	PublicBaseUrl string `json:"public_base_url"`
	ProxyPrefix   string `json:"proxy_prefix"`
	Enabled       int64  `json:"enabled"`
	CreatedAt     int64  `json:"created_at"`
	UpdatedAt     int64  `json:"updated_at"`
}

func (q *Queries) UpsertEmbyServer(ctx context.Context, arg UpsertEmbyServerParams) (UpsertEmbyServerRow, error) {
	row := q.db.QueryRowContext(ctx, upsertEmbyServer,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyRef,
		arg.PublicBaseUrl,
		arg.ProxyPrefix,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UpsertEmbyServerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.PublicBaseUrl,
		&i.ProxyPrefix,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEmbyUserLink = `-- name: UpsertEmbyUserLink :one
INSERT INTO emby_user_links (
  emby_server_id, emby_user_id, echo_user_id, enabled, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?
)
ON CONFLICT(emby_server_id, emby_user_id) DO UPDATE SET
  echo_user_id = excluded.echo_user_id,
  enabled = excluded.enabled,
  updated_at = excluded.updated_at
RETURNING id, emby_server_id, emby_user_id, emby_username, echo_user_id, enabled, created_at, updated_at
`

type UpsertEmbyUserLinkParams struct {
	EmbyServerID string `json:"emby_server_id"`
	EmbyUserID   string `json:"emby_user_id"`
	EchoUserID   string `json:"echo_user_id"`
	Enabled      int64  `json:"enabled"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) UpsertEmbyUserLink(ctx context.Context, arg UpsertEmbyUserLinkParams) (EmbyUserLink, error) {
	row := q.db.QueryRowContext(ctx, upsertEmbyUserLink,
		arg.EmbyServerID,
		arg.EmbyUserID,
		arg.EchoUserID,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EmbyUserLink
	err := row.Scan(
		&i.ID,
		&i.EmbyServerID,
		&i.EmbyUserID,
		&i.EmbyUsername,
		&i.EchoUserID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
