// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: emby_library_mappings.sql

package queries

import (
	"context"
)

const createEmbyLibraryMapping = `-- name: CreateEmbyLibraryMapping :one
INSERT INTO emby_library_mappings (
  emby_server_id, library_id, emby_path_prefix, emby_path_prefix_norm,
  echo_rel_prefix, case_sensitive, enabled, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, emby_server_id, library_id, emby_path_prefix, emby_path_prefix_norm, echo_rel_prefix, case_sensitive, enabled, created_at, updated_at
`

type CreateEmbyLibraryMappingParams struct {
	EmbyServerID       string `json:"emby_server_id"`
	LibraryID          int64  `json:"library_id"`
	EmbyPathPrefix     string `json:"emby_path_prefix"`
	EmbyPathPrefixNorm string `json:"emby_path_prefix_norm"`
	EchoRelPrefix      string `json:"echo_rel_prefix"`
	CaseSensitive      int64  `json:"case_sensitive"`
	Enabled            int64  `json:"enabled"`
	CreatedAt          int64  `json:"created_at"`
	UpdatedAt          int64  `json:"updated_at"`
}

func (q *Queries) CreateEmbyLibraryMapping(ctx context.Context, arg CreateEmbyLibraryMappingParams) (EmbyLibraryMapping, error) {
	row := q.db.QueryRowContext(ctx, createEmbyLibraryMapping,
		arg.EmbyServerID,
		arg.LibraryID,
		arg.EmbyPathPrefix,
		arg.EmbyPathPrefixNorm,
		arg.EchoRelPrefix,
		arg.CaseSensitive,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EmbyLibraryMapping
	err := row.Scan(
		&i.ID,
		&i.EmbyServerID,
		&i.LibraryID,
		&i.EmbyPathPrefix,
		&i.EmbyPathPrefixNorm,
		&i.EchoRelPrefix,
		&i.CaseSensitive,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmbyLibraryMapping = `-- name: GetEmbyLibraryMapping :one
SELECT id, emby_server_id, library_id, emby_path_prefix, emby_path_prefix_norm, echo_rel_prefix, case_sensitive, enabled, created_at, updated_at FROM emby_library_mappings
WHERE id = ? AND enabled = 1
`

type GetEmbyLibraryMappingParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetEmbyLibraryMapping(ctx context.Context, arg GetEmbyLibraryMappingParams) (EmbyLibraryMapping, error) {
	row := q.db.QueryRowContext(ctx, getEmbyLibraryMapping, arg.ID)
	var i EmbyLibraryMapping
	err := row.Scan(
		&i.ID,
		&i.EmbyServerID,
		&i.LibraryID,
		&i.EmbyPathPrefix,
		&i.EmbyPathPrefixNorm,
		&i.EchoRelPrefix,
		&i.CaseSensitive,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledEmbyLibraryMappings = `-- name: ListEnabledEmbyLibraryMappings :many
SELECT id, emby_server_id, library_id, emby_path_prefix, emby_path_prefix_norm, echo_rel_prefix, case_sensitive, enabled, created_at, updated_at FROM emby_library_mappings
WHERE emby_server_id = ? AND enabled = 1
ORDER BY length(emby_path_prefix_norm) DESC, id ASC
`

type ListEnabledEmbyLibraryMappingsParams struct {
	EmbyServerID string `json:"emby_server_id"`
}

func (q *Queries) ListEnabledEmbyLibraryMappings(ctx context.Context, arg ListEnabledEmbyLibraryMappingsParams) ([]EmbyLibraryMapping, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledEmbyLibraryMappings, arg.EmbyServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmbyLibraryMapping
	for rows.Next() {
		var i EmbyLibraryMapping
		if err := rows.Scan(
			&i.ID,
			&i.EmbyServerID,
			&i.LibraryID,
			&i.EmbyPathPrefix,
			&i.EmbyPathPrefixNorm,
			&i.EchoRelPrefix,
			&i.CaseSensitive,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEmbyLibraryMappingEnabled = `-- name: SetEmbyLibraryMappingEnabled :exec
UPDATE emby_library_mappings
SET enabled = ?, updated_at = ?
WHERE id = ?
`

type SetEmbyLibraryMappingEnabledParams struct {
	Enabled   int64 `json:"enabled"`
	UpdatedAt int64 `json:"updated_at"`
	ID        int64 `json:"id"`
}

func (q *Queries) SetEmbyLibraryMappingEnabled(ctx context.Context, arg SetEmbyLibraryMappingEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setEmbyLibraryMappingEnabled, arg.Enabled, arg.UpdatedAt, arg.ID)
	return err
}
