// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: emby_user_links.sql

package queries

import (
	"context"
	"database/sql"
)

const createEmbyUserLink = `-- name: CreateEmbyUserLink :exec
INSERT INTO emby_user_links (
  emby_server_id, emby_user_id, emby_username, echo_user_id, enabled, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?
)
`

type CreateEmbyUserLinkParams struct {
	EmbyServerID string         `json:"emby_server_id"`
	EmbyUserID   string         `json:"emby_user_id"`
	EmbyUsername sql.NullString `json:"emby_username"`
	EchoUserID   string         `json:"echo_user_id"`
	Enabled      int64          `json:"enabled"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

func (q *Queries) CreateEmbyUserLink(ctx context.Context, arg CreateEmbyUserLinkParams) error {
	_, err := q.db.ExecContext(ctx, createEmbyUserLink,
		arg.EmbyServerID,
		arg.EmbyUserID,
		arg.EmbyUsername,
		arg.EchoUserID,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getEmbyUserLink = `-- name: GetEmbyUserLink :one
SELECT id, emby_server_id, emby_user_id, emby_username, echo_user_id, enabled, created_at, updated_at FROM emby_user_links
WHERE emby_server_id = ? AND emby_user_id = ? AND enabled = 1
`

type GetEmbyUserLinkParams struct {
	EmbyServerID string `json:"emby_server_id"`
	EmbyUserID   string `json:"emby_user_id"`
}

func (q *Queries) GetEmbyUserLink(ctx context.Context, arg GetEmbyUserLinkParams) (EmbyUserLink, error) {
	row := q.db.QueryRowContext(ctx, getEmbyUserLink, arg.EmbyServerID, arg.EmbyUserID)
	var i EmbyUserLink
	err := row.Scan(
		&i.ID,
		&i.EmbyServerID,
		&i.EmbyUserID,
		&i.EmbyUsername,
		&i.EchoUserID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
