// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: emby_servers.sql

package queries

import (
	"context"
	"database/sql"
)

const createEmbyServer = `-- name: CreateEmbyServer :exec
INSERT INTO emby_servers (
  id, name, base_url, api_key_ref, public_base_url, proxy_prefix, enabled, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateEmbyServerParams struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	BaseUrl       string         `json:"base_url"`
	ApiKeyRef     sql.NullString `json:"api_key_ref"`
	PublicBaseUrl string         `json:"public_base_url"`
	ProxyPrefix   string         `json:"proxy_prefix"`
	Enabled       int64          `json:"enabled"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

func (q *Queries) CreateEmbyServer(ctx context.Context, arg CreateEmbyServerParams) error {
	_, err := q.db.ExecContext(ctx, createEmbyServer,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyRef,
		arg.PublicBaseUrl,
		arg.ProxyPrefix,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getEnabledEmbyServer = `-- name: GetEnabledEmbyServer :one
SELECT id, name, base_url, api_key_ref, public_base_url, proxy_prefix, enabled, created_at, updated_at FROM emby_servers
WHERE id = ? AND enabled = 1
`

type GetEnabledEmbyServerParams struct {
	ID string `json:"id"`
}

func (q *Queries) GetEnabledEmbyServer(ctx context.Context, arg GetEnabledEmbyServerParams) (EmbyServer, error) {
	row := q.db.QueryRowContext(ctx, getEnabledEmbyServer, arg.ID)
	var i EmbyServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyRef,
		&i.PublicBaseUrl,
		&i.ProxyPrefix,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
