// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hash_conflicts.sql

package queries

import (
	"context"
)

const countOpenHashConflicts = `-- name: CountOpenHashConflicts :one
SELECT COUNT(*) FROM hash_conflicts
WHERE status = 'open'
`

func (q *Queries) CountOpenHashConflicts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenHashConflicts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getHashConflict = `-- name: GetHashConflict :one
SELECT id, blob_id_a, blob_id_b, reason, detail, observed_at, status FROM hash_conflicts
WHERE id = ?
`

type GetHashConflictParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetHashConflict(ctx context.Context, arg GetHashConflictParams) (HashConflict, error) {
	row := q.db.QueryRowContext(ctx, getHashConflict, arg.ID)
	var i HashConflict
	err := row.Scan(
		&i.ID,
		&i.BlobIDA,
		&i.BlobIDB,
		&i.Reason,
		&i.Detail,
		&i.ObservedAt,
		&i.Status,
	)
	return i, err
}

const insertHashConflict = `-- name: InsertHashConflict :one
INSERT INTO hash_conflicts (
  blob_id_a, blob_id_b, reason, detail, observed_at, status
) VALUES (
  ?, ?, ?, ?, ?, ?
)
RETURNING id, blob_id_a, blob_id_b, reason, detail, observed_at, status
`

type InsertHashConflictParams struct {
	BlobIDA    int64  `json:"blob_id_a"`
	BlobIDB    int64  `json:"blob_id_b"`
	Reason     string `json:"reason"`
	Detail     string `json:"detail"`
	ObservedAt int64  `json:"observed_at"`
	Status     string `json:"status"`
}

func (q *Queries) InsertHashConflict(ctx context.Context, arg InsertHashConflictParams) (HashConflict, error) {
	row := q.db.QueryRowContext(ctx, insertHashConflict,
		arg.BlobIDA,
		arg.BlobIDB,
		arg.Reason,
		arg.Detail,
		arg.ObservedAt,
		arg.Status,
	)
	var i HashConflict
	err := row.Scan(
		&i.ID,
		&i.BlobIDA,
		&i.BlobIDB,
		&i.Reason,
		&i.Detail,
		&i.ObservedAt,
		&i.Status,
	)
	return i, err
}

const listOpenHashConflicts = `-- name: ListOpenHashConflicts :many
SELECT id, blob_id_a, blob_id_b, reason, detail, observed_at, status FROM hash_conflicts
WHERE status = 'open'
ORDER BY observed_at DESC
LIMIT ? OFFSET ?
`

type ListOpenHashConflictsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListOpenHashConflicts(ctx context.Context, arg ListOpenHashConflictsParams) ([]HashConflict, error) {
	rows, err := q.db.QueryContext(ctx, listOpenHashConflicts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HashConflict
	for rows.Next() {
		var i HashConflict
		if err := rows.Scan(
			&i.ID,
			&i.BlobIDA,
			&i.BlobIDB,
			&i.Reason,
			&i.Detail,
			&i.ObservedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHashConflictStatus = `-- name: UpdateHashConflictStatus :exec
UPDATE hash_conflicts
SET status = ?
WHERE id = ?
`

type UpdateHashConflictStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateHashConflictStatus(ctx context.Context, arg UpdateHashConflictStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateHashConflictStatus, arg.Status, arg.ID)
	return err
}
