// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package queries

import (
	"context"
	"database/sql"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
  kind, status, payload, progress, error, owner_id, created_at, started_at, finished_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, kind, status, payload, progress, error, owner_id, created_at, started_at, finished_at
`

type CreateJobParams struct {
	Kind       string         `json:"kind"`
	Status     string         `json:"status"`
	Payload    string         `json:"payload"`
	Progress   sql.NullString `json:"progress"`
	Error      sql.NullString `json:"error"`
	OwnerID    string         `json:"owner_id"`
	CreatedAt  int64          `json:"created_at"`
	StartedAt  sql.NullInt64  `json:"started_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.Kind,
		arg.Status,
		arg.Payload,
		arg.Progress,
		arg.Error,
		arg.OwnerID,
		arg.CreatedAt,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Payload,
		&i.Progress,
		&i.Error,
		&i.OwnerID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = ?
`

type DeleteJobParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) DeleteJob(ctx context.Context, arg DeleteJobParams) error {
	_, err := q.db.ExecContext(ctx, deleteJob, arg.ID)
	return err
}

const finishJob = `-- name: FinishJob :exec
UPDATE jobs
SET status = ?,
    error = ?,
    finished_at = ?
WHERE id = ?
`

type FinishJobParams struct {
	Status     string         `json:"status"`
	Error      sql.NullString `json:"error"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
	ID         int64          `json:"id"`
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.ExecContext(ctx, finishJob,
		arg.Status,
		arg.Error,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, kind, status, payload, progress, error, owner_id, created_at, started_at, finished_at FROM jobs
WHERE id = ?
`

type GetJobParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Payload,
		&i.Progress,
		&i.Error,
		&i.OwnerID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listJobsByStatus = `-- name: ListJobsByStatus :many
SELECT id, kind, status, payload, progress, error, owner_id, created_at, started_at, finished_at FROM jobs
WHERE status = ?
ORDER BY created_at, id
LIMIT ?
`

type ListJobsByStatusParams struct {
	Status string `json:"status"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListJobsByStatus(ctx context.Context, arg ListJobsByStatusParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.Payload,
			&i.Progress,
			&i.Error,
			&i.OwnerID,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobRunning = `-- name: MarkJobRunning :exec
UPDATE jobs
SET status = 'running',
    started_at = ?
WHERE id = ?
`

type MarkJobRunningParams struct {
	StartedAt sql.NullInt64 `json:"started_at"`
	ID        int64         `json:"id"`
}

func (q *Queries) MarkJobRunning(ctx context.Context, arg MarkJobRunningParams) error {
	_, err := q.db.ExecContext(ctx, markJobRunning, arg.StartedAt, arg.ID)
	return err
}

const updateJobProgress = `-- name: UpdateJobProgress :exec
UPDATE jobs
SET progress = ?
WHERE id = ?
`

type UpdateJobProgressParams struct {
	Progress sql.NullString `json:"progress"`
	ID       int64          `json:"id"`
}

func (q *Queries) UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateJobProgress, arg.Progress, arg.ID)
	return err
}
