// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: libraries.sql

package queries

import (
	"context"
)

const createLibrary = `-- name: CreateLibrary :one
INSERT INTO libraries (
  name, echo_output_kind, echo_output_path, owner_id, created_at
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id, name, echo_output_kind, echo_output_path, owner_id, created_at
`

type CreateLibraryParams struct {
	Name           string `json:"name"`
	EchoOutputKind string `json:"echo_output_kind"`
	EchoOutputPath string `json:"echo_output_path"`
	OwnerID        string `json:"owner_id"`
	CreatedAt      int64  `json:"created_at"`
}

func (q *Queries) CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error) {
	row := q.db.QueryRowContext(ctx, createLibrary,
		arg.Name,
		arg.EchoOutputKind,
		arg.EchoOutputPath,
		arg.OwnerID,
		arg.CreatedAt,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EchoOutputKind,
		&i.EchoOutputPath,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLibrary = `-- name: DeleteLibrary :exec
DELETE FROM libraries
WHERE id = ?
`

type DeleteLibraryParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) DeleteLibrary(ctx context.Context, arg DeleteLibraryParams) error {
	_, err := q.db.ExecContext(ctx, deleteLibrary, arg.ID)
	return err
}

const getLibrary = `-- name: GetLibrary :one
SELECT id, name, echo_output_kind, echo_output_path, owner_id, created_at FROM libraries
WHERE id = ?
`

type GetLibraryParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetLibrary(ctx context.Context, arg GetLibraryParams) (Library, error) {
	row := q.db.QueryRowContext(ctx, getLibrary, arg.ID)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EchoOutputKind,
		&i.EchoOutputPath,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const listLibraries = `-- name: ListLibraries :many
SELECT id, name, echo_output_kind, echo_output_path, owner_id, created_at FROM libraries
ORDER BY id
`

func (q *Queries) ListLibraries(ctx context.Context) ([]Library, error) {
	rows, err := q.db.QueryContext(ctx, listLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Library
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EchoOutputKind,
			&i.EchoOutputPath,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLibrary = `-- name: UpdateLibrary :exec
UPDATE libraries
SET name = ?,
    echo_output_kind = ?,
    echo_output_path = ?,
    owner_id = ?
WHERE id = ?
`

type UpdateLibraryParams struct {
	Name           string `json:"name"`
	EchoOutputKind string `json:"echo_output_kind"`
	EchoOutputPath string `json:"echo_output_path"`
	OwnerID        string `json:"owner_id"`
	ID             int64  `json:"id"`
}

func (q *Queries) UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) error {
	_, err := q.db.ExecContext(ctx, updateLibrary,
		arg.Name,
		arg.EchoOutputKind,
		arg.EchoOutputPath,
		arg.OwnerID,
		arg.ID,
	)
	return err
}
