// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: library_grants.sql

package queries

import (
	"context"
	"database/sql"
)

const grantLibraryPlayback = `-- name: GrantLibraryPlayback :exec
INSERT INTO library_grants (
  library_id, echo_user_id, permission, enabled, created_by, created_at, updated_at
) VALUES (
  ?, ?, 'playback', 1, ?, ?, ?
)
ON CONFLICT(library_id, echo_user_id, permission) DO UPDATE
SET enabled = 1, updated_at = excluded.updated_at
`

type GrantLibraryPlaybackParams struct {
	LibraryID  int64          `json:"library_id"`
	EchoUserID string         `json:"echo_user_id"`
	CreatedBy  sql.NullString `json:"created_by"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) GrantLibraryPlayback(ctx context.Context, arg GrantLibraryPlaybackParams) error {
	_, err := q.db.ExecContext(ctx, grantLibraryPlayback,
		arg.LibraryID,
		arg.EchoUserID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const userCanPlaybackLibrary = `-- name: UserCanPlaybackLibrary :one
SELECT EXISTS (
  SELECT 1 FROM libraries
  WHERE libraries.id = ?1 AND owner_id = ?2
  UNION
  SELECT 1 FROM library_grants
  WHERE library_id = ?1
    AND echo_user_id = ?2
    AND permission = 'playback'
    AND enabled = 1
) AS allowed
`

type UserCanPlaybackLibraryParams struct {
	LibraryID  int64  `json:"library_id"`
	EchoUserID string `json:"echo_user_id"`
}

func (q *Queries) UserCanPlaybackLibrary(ctx context.Context, arg UserCanPlaybackLibraryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, userCanPlaybackLibrary, arg.LibraryID, arg.EchoUserID)
	var allowed int64
	err := row.Scan(&allowed)
	return allowed, err
}
