// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_subscriptions.sql

package queries

import (
	"context"
	"database/sql"
)

const countActiveUserMediaSubscriptions = `-- name: CountActiveUserMediaSubscriptions :one
SELECT COUNT(*) FROM user_media_subscriptions
WHERE echo_user_id = ?1
  AND status = 'active'
`

type CountActiveUserMediaSubscriptionsParams struct {
	EchoUserID string `json:"echo_user_id"`
}

func (q *Queries) CountActiveUserMediaSubscriptions(ctx context.Context, arg CountActiveUserMediaSubscriptionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveUserMediaSubscriptions, arg.EchoUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findCanonicalDiscoverySubscriptionForMediaRequest = `-- name: FindCanonicalDiscoverySubscriptionForMediaRequest :one
SELECT id, owner_id, tmdb_id, media_type, tmdb_language, title_snapshot, library_id, producer_profile_id, rule_profile_id, status, season_filter_json, current_best_match_id, current_best_score_json, next_check_at, locked_until, last_checked_at, failure_count, last_error_kind, last_error_message, created_at, updated_at FROM discovery_subscriptions
WHERE tmdb_id = ?1
  AND media_type = ?2
  AND owner_id = ?3
  AND library_id = ?4
`

type FindCanonicalDiscoverySubscriptionForMediaRequestParams struct {
	TmdbID    string `json:"tmdb_id"`
	MediaType string `json:"media_type"`
	OwnerID   string `json:"owner_id"`
	LibraryID int64  `json:"library_id"`
}

func (q *Queries) FindCanonicalDiscoverySubscriptionForMediaRequest(ctx context.Context, arg FindCanonicalDiscoverySubscriptionForMediaRequestParams) (DiscoverySubscription, error) {
	row := q.db.QueryRowContext(ctx, findCanonicalDiscoverySubscriptionForMediaRequest,
		arg.TmdbID,
		arg.MediaType,
		arg.OwnerID,
		arg.LibraryID,
	)
	var i DiscoverySubscription
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TmdbID,
		&i.MediaType,
		&i.TmdbLanguage,
		&i.TitleSnapshot,
		&i.LibraryID,
		&i.ProducerProfileID,
		&i.RuleProfileID,
		&i.Status,
		&i.SeasonFilterJson,
		&i.CurrentBestMatchID,
		&i.CurrentBestScoreJson,
		&i.NextCheckAt,
		&i.LockedUntil,
		&i.LastCheckedAt,
		&i.FailureCount,
		&i.LastErrorKind,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserMediaSubscriptionForUser = `-- name: GetUserMediaSubscriptionForUser :one
SELECT id, echo_user_id, request_id, discovery_subscription_id, tmdb_id, media_type, season_filter_json, season_filter_key, status, created_at, updated_at FROM user_media_subscriptions
WHERE id = ?1
  AND echo_user_id = ?2
`

type GetUserMediaSubscriptionForUserParams struct {
	ID         int64  `json:"id"`
	EchoUserID string `json:"echo_user_id"`
}

func (q *Queries) GetUserMediaSubscriptionForUser(ctx context.Context, arg GetUserMediaSubscriptionForUserParams) (UserMediaSubscription, error) {
	row := q.db.QueryRowContext(ctx, getUserMediaSubscriptionForUser, arg.ID, arg.EchoUserID)
	var i UserMediaSubscription
	err := row.Scan(
		&i.ID,
		&i.EchoUserID,
		&i.RequestID,
		&i.DiscoverySubscriptionID,
		&i.TmdbID,
		&i.MediaType,
		&i.SeasonFilterJson,
		&i.SeasonFilterKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserMediaSubscriptionsForUser = `-- name: ListUserMediaSubscriptionsForUser :many
SELECT id, echo_user_id, request_id, discovery_subscription_id, tmdb_id, media_type, season_filter_json, season_filter_key, status, created_at, updated_at FROM user_media_subscriptions
WHERE echo_user_id = ?1
ORDER BY updated_at DESC, id DESC
LIMIT ?3 OFFSET ?2
`

type ListUserMediaSubscriptionsForUserParams struct {
	EchoUserID string `json:"echo_user_id"`
	Offset     int64  `json:"offset"`
	Limit      int64  `json:"limit"`
}

func (q *Queries) ListUserMediaSubscriptionsForUser(ctx context.Context, arg ListUserMediaSubscriptionsForUserParams) ([]UserMediaSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listUserMediaSubscriptionsForUser, arg.EchoUserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserMediaSubscription
	for rows.Next() {
		var i UserMediaSubscription
		if err := rows.Scan(
			&i.ID,
			&i.EchoUserID,
			&i.RequestID,
			&i.DiscoverySubscriptionID,
			&i.TmdbID,
			&i.MediaType,
			&i.SeasonFilterJson,
			&i.SeasonFilterKey,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectUserMediaSubscriptionStatus = `-- name: ProjectUserMediaSubscriptionStatus :one
SELECT
  ums.id AS user_media_subscription_id,
  ums.status AS user_subscription_status,
  ums.tmdb_id AS tmdb_id,
  ums.media_type AS media_type,
  ums.season_filter_json AS season_filter_json,
  ds.status AS discovery_subscription_status,
  ds.tmdb_language AS tmdb_language,
  ds.title_snapshot AS title_snapshot,
  l.id AS target_library_id,
  l.name AS target_library_name,
  ums.created_at AS created_at,
  ums.updated_at AS updated_at
FROM user_media_subscriptions AS ums
JOIN discovery_subscriptions AS ds ON ds.id = ums.discovery_subscription_id
JOIN libraries AS l ON l.id = ds.library_id
WHERE ums.id = ?1
  AND ums.echo_user_id = ?2
`

type ProjectUserMediaSubscriptionStatusParams struct {
	ID         int64  `json:"id"`
	EchoUserID string `json:"echo_user_id"`
}

type ProjectUserMediaSubscriptionStatusRow struct {
	UserMediaSubscriptionID     int64          `json:"user_media_subscription_id"`
	UserSubscriptionStatus      string         `json:"user_subscription_status"`
	TmdbID                      string         `json:"tmdb_id"`
	MediaType                   string         `json:"media_type"`
	SeasonFilterJson            sql.NullString `json:"season_filter_json"`
	DiscoverySubscriptionStatus string         `json:"discovery_subscription_status"`
	TmdbLanguage                string         `json:"tmdb_language"`
	TitleSnapshot               string         `json:"title_snapshot"`
	TargetLibraryID             int64          `json:"target_library_id"`
	TargetLibraryName           string         `json:"target_library_name"`
	CreatedAt                   int64          `json:"created_at"`
	UpdatedAt                   int64          `json:"updated_at"`
}

func (q *Queries) ProjectUserMediaSubscriptionStatus(ctx context.Context, arg ProjectUserMediaSubscriptionStatusParams) (ProjectUserMediaSubscriptionStatusRow, error) {
	row := q.db.QueryRowContext(ctx, projectUserMediaSubscriptionStatus, arg.ID, arg.EchoUserID)
	var i ProjectUserMediaSubscriptionStatusRow
	err := row.Scan(
		&i.UserMediaSubscriptionID,
		&i.UserSubscriptionStatus,
		&i.TmdbID,
		&i.MediaType,
		&i.SeasonFilterJson,
		&i.DiscoverySubscriptionStatus,
		&i.TmdbLanguage,
		&i.TitleSnapshot,
		&i.TargetLibraryID,
		&i.TargetLibraryName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserMediaSubscriptionStatus = `-- name: UpdateUserMediaSubscriptionStatus :one
UPDATE user_media_subscriptions
SET status = ?1,
    updated_at = ?2
WHERE id = ?3
  AND echo_user_id = ?4
RETURNING id, echo_user_id, request_id, discovery_subscription_id, tmdb_id, media_type, season_filter_json, season_filter_key, status, created_at, updated_at
`

type UpdateUserMediaSubscriptionStatusParams struct {
	Status     string `json:"status"`
	UpdatedAt  int64  `json:"updated_at"`
	ID         int64  `json:"id"`
	EchoUserID string `json:"echo_user_id"`
}

func (q *Queries) UpdateUserMediaSubscriptionStatus(ctx context.Context, arg UpdateUserMediaSubscriptionStatusParams) (UserMediaSubscription, error) {
	row := q.db.QueryRowContext(ctx, updateUserMediaSubscriptionStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.EchoUserID,
	)
	var i UserMediaSubscription
	err := row.Scan(
		&i.ID,
		&i.EchoUserID,
		&i.RequestID,
		&i.DiscoverySubscriptionID,
		&i.TmdbID,
		&i.MediaType,
		&i.SeasonFilterJson,
		&i.SeasonFilterKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDiscoverySubscriptionForMediaRequest = `-- name: UpsertDiscoverySubscriptionForMediaRequest :one
INSERT INTO discovery_subscriptions (
  owner_id, tmdb_id, media_type, tmdb_language, title_snapshot, library_id,
  producer_profile_id, rule_profile_id, status, season_filter_json,
  next_check_at, created_at, updated_at
) VALUES (
  ?1, ?2, ?3,
  ?4, ?5, ?6,
  ?7, ?8, ?9,
  ?10, ?11, ?12,
  ?13
)
ON CONFLICT(tmdb_id, media_type, owner_id, library_id) DO UPDATE SET
  updated_at = discovery_subscriptions.updated_at
RETURNING id, owner_id, tmdb_id, media_type, tmdb_language, title_snapshot, library_id, producer_profile_id, rule_profile_id, status, season_filter_json, current_best_match_id, current_best_score_json, next_check_at, locked_until, last_checked_at, failure_count, last_error_kind, last_error_message, created_at, updated_at
`

type UpsertDiscoverySubscriptionForMediaRequestParams struct {
	OwnerID           string         `json:"owner_id"`
	TmdbID            string         `json:"tmdb_id"`
	MediaType         string         `json:"media_type"`
	TmdbLanguage      string         `json:"tmdb_language"`
	TitleSnapshot     string         `json:"title_snapshot"`
	LibraryID         int64          `json:"library_id"`
	ProducerProfileID int64          `json:"producer_profile_id"`
	RuleProfileID     int64          `json:"rule_profile_id"`
	Status            string         `json:"status"`
	SeasonFilterJson  sql.NullString `json:"season_filter_json"`
	NextCheckAt       sql.NullInt64  `json:"next_check_at"`
	CreatedAt         int64          `json:"created_at"`
	UpdatedAt         int64          `json:"updated_at"`
}

func (q *Queries) UpsertDiscoverySubscriptionForMediaRequest(ctx context.Context, arg UpsertDiscoverySubscriptionForMediaRequestParams) (DiscoverySubscription, error) {
	row := q.db.QueryRowContext(ctx, upsertDiscoverySubscriptionForMediaRequest,
		arg.OwnerID,
		arg.TmdbID,
		arg.MediaType,
		arg.TmdbLanguage,
		arg.TitleSnapshot,
		arg.LibraryID,
		arg.ProducerProfileID,
		arg.RuleProfileID,
		arg.Status,
		arg.SeasonFilterJson,
		arg.NextCheckAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DiscoverySubscription
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TmdbID,
		&i.MediaType,
		&i.TmdbLanguage,
		&i.TitleSnapshot,
		&i.LibraryID,
		&i.ProducerProfileID,
		&i.RuleProfileID,
		&i.Status,
		&i.SeasonFilterJson,
		&i.CurrentBestMatchID,
		&i.CurrentBestScoreJson,
		&i.NextCheckAt,
		&i.LockedUntil,
		&i.LastCheckedAt,
		&i.FailureCount,
		&i.LastErrorKind,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserMediaSubscription = `-- name: UpsertUserMediaSubscription :one
INSERT INTO user_media_subscriptions (
  echo_user_id, request_id, discovery_subscription_id, tmdb_id, media_type,
  season_filter_json, season_filter_key, status, created_at, updated_at
) VALUES (
  ?1, ?2,
  ?3, ?4, ?5,
  ?6, ?7, ?8,
  ?9, ?10
)
ON CONFLICT(echo_user_id, discovery_subscription_id, season_filter_key) DO UPDATE SET
  request_id = COALESCE(excluded.request_id, user_media_subscriptions.request_id),
  tmdb_id = excluded.tmdb_id,
  media_type = excluded.media_type,
  season_filter_json = excluded.season_filter_json,
  status = excluded.status,
  updated_at = excluded.updated_at
RETURNING id, echo_user_id, request_id, discovery_subscription_id, tmdb_id, media_type, season_filter_json, season_filter_key, status, created_at, updated_at
`

type UpsertUserMediaSubscriptionParams struct {
	EchoUserID              string         `json:"echo_user_id"`
	RequestID               sql.NullInt64  `json:"request_id"`
	DiscoverySubscriptionID int64          `json:"discovery_subscription_id"`
	TmdbID                  string         `json:"tmdb_id"`
	MediaType               string         `json:"media_type"`
	SeasonFilterJson        sql.NullString `json:"season_filter_json"`
	SeasonFilterKey         string         `json:"season_filter_key"`
	Status                  string         `json:"status"`
	CreatedAt               int64          `json:"created_at"`
	UpdatedAt               int64          `json:"updated_at"`
}

func (q *Queries) UpsertUserMediaSubscription(ctx context.Context, arg UpsertUserMediaSubscriptionParams) (UserMediaSubscription, error) {
	row := q.db.QueryRowContext(ctx, upsertUserMediaSubscription,
		arg.EchoUserID,
		arg.RequestID,
		arg.DiscoverySubscriptionID,
		arg.TmdbID,
		arg.MediaType,
		arg.SeasonFilterJson,
		arg.SeasonFilterKey,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserMediaSubscription
	err := row.Scan(
		&i.ID,
		&i.EchoUserID,
		&i.RequestID,
		&i.DiscoverySubscriptionID,
		&i.TmdbID,
		&i.MediaType,
		&i.SeasonFilterJson,
		&i.SeasonFilterKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
