// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Account struct {
	ID               string         `json:"id"`
	Provider         string         `json:"provider"`
	SidecarID        string         `json:"sidecar_id"`
	StorageMount     string         `json:"storage_mount"`
	Status           string         `json:"status"`
	LastCheck        sql.NullInt64  `json:"last_check"`
	OwnerID          string         `json:"owner_id"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	SchedulerState   string         `json:"scheduler_state"`
	CooldownUntil    sql.NullInt64  `json:"cooldown_until"`
	RecheckAfter     sql.NullInt64  `json:"recheck_after"`
	StatusReason     sql.NullString `json:"status_reason"`
	LastErrorAt      sql.NullInt64  `json:"last_error_at"`
	LastErrorKind    sql.NullString `json:"last_error_kind"`
	LastErrorMessage sql.NullString `json:"last_error_message"`
}

type AccountPoolAssignment struct {
	ID                   int64         `json:"id"`
	EchoUserID           string        `json:"echo_user_id"`
	AccountID            string        `json:"account_id"`
	Provider             string        `json:"provider"`
	Priority             int64         `json:"priority"`
	Weight               int64         `json:"weight"`
	MaxConcurrentStreams sql.NullInt64 `json:"max_concurrent_streams"`
	DailyBytesLimit      sql.NullInt64 `json:"daily_bytes_limit"`
	Enabled              int64         `json:"enabled"`
	CreatedAt            int64         `json:"created_at"`
	UpdatedAt            int64         `json:"updated_at"`
}

type ApiToken struct {
	ID         string        `json:"id"`
	UserID     string        `json:"user_id"`
	Name       string        `json:"name"`
	TokenHash  string        `json:"token_hash"`
	Scopes     string        `json:"scopes"`
	ExpiresAt  sql.NullInt64 `json:"expires_at"`
	LastUsedAt sql.NullInt64 `json:"last_used_at"`
	CreatedAt  int64         `json:"created_at"`
	RevokedAt  sql.NullInt64 `json:"revoked_at"`
}

type Blob struct {
	ID            int64          `json:"id"`
	Size          int64          `json:"size"`
	CanonicalName sql.NullString `json:"canonical_name"`
	SourceMtime   sql.NullInt64  `json:"source_mtime"`
	OwnerID       string         `json:"owner_id"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

type BlobHash struct {
	ID            int64  `json:"id"`
	BlobID        int64  `json:"blob_id"`
	HashType      string `json:"hash_type"`
	HashValue     string `json:"hash_value"`
	HashValueNorm string `json:"hash_value_norm"`
	Size          int64  `json:"size"`
}

type CopyFailure struct {
	ID            int64          `json:"id"`
	CopyID        sql.NullInt64  `json:"copy_id"`
	AccountID     sql.NullString `json:"account_id"`
	SidecarID     string         `json:"sidecar_id"`
	StorageMount  string         `json:"storage_mount"`
	Operation     string         `json:"operation"`
	Kind          string         `json:"kind"`
	Confidence    string         `json:"confidence"`
	EvidenceClass string         `json:"evidence_class"`
	HttpStatus    sql.NullInt64  `json:"http_status"`
	OpenlistCode  sql.NullInt64  `json:"openlist_code"`
	SafeMessage   sql.NullString `json:"safe_message"`
	ObservedAt    int64          `json:"observed_at"`
	RequestID     sql.NullString `json:"request_id"`
}

type DiscoveredResource struct {
	ID               int64          `json:"id"`
	SourceID         int64          `json:"source_id"`
	Provider         string         `json:"provider"`
	LinkKind         string         `json:"link_kind"`
	ExternalKey      string         `json:"external_key"`
	TmdbID           sql.NullString `json:"tmdb_id"`
	MediaType        sql.NullString `json:"media_type"`
	Title            sql.NullString `json:"title"`
	SeasonNumber     sql.NullInt64  `json:"season_number"`
	EpisodeStart     sql.NullInt64  `json:"episode_start"`
	EpisodeEnd       sql.NullInt64  `json:"episode_end"`
	ShareCode        sql.NullString `json:"share_code"`
	ReceiveCode      sql.NullString `json:"receive_code"`
	ShareUrlRedacted sql.NullString `json:"share_url_redacted"`
	RawTextRedacted  sql.NullString `json:"raw_text_redacted"`
	RawTextRef       sql.NullString `json:"raw_text_ref"`
	ParsedJson       string         `json:"parsed_json"`
	FeatureJson      string         `json:"feature_json"`
	Status           string         `json:"status"`
	FirstSeenAt      int64          `json:"first_seen_at"`
	LastSeenAt       int64          `json:"last_seen_at"`
}

type DiscoveryAccessPolicy struct {
	ID                     int64          `json:"id"`
	Name                   string         `json:"name"`
	Enabled                int64          `json:"enabled"`
	Priority               int64          `json:"priority"`
	SubjectUserID          sql.NullString `json:"subject_user_id"`
	RequestMode            string         `json:"request_mode"`
	CanSearch              int64          `json:"can_search"`
	MaxPendingRequests     sql.NullInt64  `json:"max_pending_requests"`
	MaxActiveSubscriptions sql.NullInt64  `json:"max_active_subscriptions"`
	RequestCooldownSeconds sql.NullInt64  `json:"request_cooldown_seconds"`
	CreatedBy              sql.NullString `json:"created_by"`
	CreatedAt              int64          `json:"created_at"`
	UpdatedAt              int64          `json:"updated_at"`
}

type DiscoveryPolicyTarget struct {
	ID                      int64          `json:"id"`
	PolicyID                int64          `json:"policy_id"`
	Label                   string         `json:"label"`
	LibraryID               int64          `json:"library_id"`
	ProducerProfileID       int64          `json:"producer_profile_id"`
	RuleProfileID           int64          `json:"rule_profile_id"`
	PipelineOwnerID         string         `json:"pipeline_owner_id"`
	MediaType               sql.NullString `json:"media_type"`
	MatchMode               string         `json:"match_mode"`
	GrantPlaybackOnApproval int64          `json:"grant_playback_on_approval"`
	Enabled                 int64          `json:"enabled"`
	DefaultTarget           int64          `json:"default_target"`
	CreatedAt               int64          `json:"created_at"`
	UpdatedAt               int64          `json:"updated_at"`
}

type DiscoveryProducerProfile struct {
	ID                     int64  `json:"id"`
	Name                   string `json:"name"`
	Provider               string `json:"provider"`
	Tool                   string `json:"tool"`
	TargetAccount          string `json:"target_account"`
	TargetSubdirTemplate   string `json:"target_subdir_template"`
	LibraryRelPathTemplate string `json:"library_rel_path_template"`
	DefaultArgsJson        string `json:"default_args_json"`
	Enabled                int64  `json:"enabled"`
	CreatedAt              int64  `json:"created_at"`
	UpdatedAt              int64  `json:"updated_at"`
}

type DiscoveryRawAccessEvent struct {
	ID            int64          `json:"id"`
	ResourceID    int64          `json:"resource_id"`
	ActorUserID   string         `json:"actor_user_id"`
	RequestID     sql.NullString `json:"request_id"`
	ResponseBytes int64          `json:"response_bytes"`
	Redacted      int64          `json:"redacted"`
	AccessedAt    int64          `json:"accessed_at"`
}

type DiscoveryRun struct {
	ID             int64          `json:"id"`
	Kind           string         `json:"kind"`
	SourceID       sql.NullInt64  `json:"source_id"`
	SubscriptionID sql.NullInt64  `json:"subscription_id"`
	JobID          sql.NullInt64  `json:"job_id"`
	Status         string         `json:"status"`
	CountersJson   string         `json:"counters_json"`
	ErrorKind      sql.NullString `json:"error_kind"`
	ErrorMessage   sql.NullString `json:"error_message"`
	StartedAt      sql.NullInt64  `json:"started_at"`
	FinishedAt     sql.NullInt64  `json:"finished_at"`
	CreatedAt      int64          `json:"created_at"`
}

type DiscoverySource struct {
	ID               int64          `json:"id"`
	Kind             string         `json:"kind"`
	Name             string         `json:"name"`
	Enabled          int64          `json:"enabled"`
	ConfigJson       string         `json:"config_json"`
	SecretRef        sql.NullString `json:"secret_ref"`
	RateLimitJson    sql.NullString `json:"rate_limit_json"`
	SchedulerState   string         `json:"scheduler_state"`
	NextRunAt        sql.NullInt64  `json:"next_run_at"`
	LockedUntil      sql.NullInt64  `json:"locked_until"`
	BackoffUntil     sql.NullInt64  `json:"backoff_until"`
	FailureCount     int64          `json:"failure_count"`
	LastSuccessAt    sql.NullInt64  `json:"last_success_at"`
	LastErrorKind    sql.NullString `json:"last_error_kind"`
	LastErrorMessage sql.NullString `json:"last_error_message"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

type DiscoverySubscription struct {
	ID                   int64          `json:"id"`
	OwnerID              string         `json:"owner_id"`
	TmdbID               string         `json:"tmdb_id"`
	MediaType            string         `json:"media_type"`
	TmdbLanguage         string         `json:"tmdb_language"`
	TitleSnapshot        string         `json:"title_snapshot"`
	LibraryID            int64          `json:"library_id"`
	ProducerProfileID    int64          `json:"producer_profile_id"`
	RuleProfileID        int64          `json:"rule_profile_id"`
	Status               string         `json:"status"`
	SeasonFilterJson     sql.NullString `json:"season_filter_json"`
	CurrentBestMatchID   sql.NullInt64  `json:"current_best_match_id"`
	CurrentBestScoreJson sql.NullString `json:"current_best_score_json"`
	NextCheckAt          sql.NullInt64  `json:"next_check_at"`
	LockedUntil          sql.NullInt64  `json:"locked_until"`
	LastCheckedAt        sql.NullInt64  `json:"last_checked_at"`
	FailureCount         int64          `json:"failure_count"`
	LastErrorKind        sql.NullString `json:"last_error_kind"`
	LastErrorMessage     sql.NullString `json:"last_error_message"`
	CreatedAt            int64          `json:"created_at"`
	UpdatedAt            int64          `json:"updated_at"`
}

type DiscoverySubscriptionRequest struct {
	ID                          int64          `json:"id"`
	RequesterUserID             string         `json:"requester_user_id"`
	Status                      string         `json:"status"`
	TmdbID                      string         `json:"tmdb_id"`
	MediaType                   string         `json:"media_type"`
	TmdbLanguage                string         `json:"tmdb_language"`
	TitleSnapshot               string         `json:"title_snapshot"`
	OriginalTitleSnapshot       sql.NullString `json:"original_title_snapshot"`
	ReleaseYearSnapshot         sql.NullInt64  `json:"release_year_snapshot"`
	PosterPathSnapshot          sql.NullString `json:"poster_path_snapshot"`
	SeasonFilterJson            sql.NullString `json:"season_filter_json"`
	PolicyIDSnapshot            sql.NullInt64  `json:"policy_id_snapshot"`
	PolicyTargetIDSnapshot      sql.NullInt64  `json:"policy_target_id_snapshot"`
	TargetLabelSnapshot         string         `json:"target_label_snapshot"`
	TargetLibraryID             int64          `json:"target_library_id"`
	TargetLibraryNameSnapshot   string         `json:"target_library_name_snapshot"`
	ProducerProfileIDSnapshot   int64          `json:"producer_profile_id_snapshot"`
	ProducerProfileNameSnapshot string         `json:"producer_profile_name_snapshot"`
	RuleProfileIDSnapshot       int64          `json:"rule_profile_id_snapshot"`
	RuleProfileVersionSnapshot  int64          `json:"rule_profile_version_snapshot"`
	UserNote                    sql.NullString `json:"user_note"`
	AdminNote                   sql.NullString `json:"admin_note"`
	ReviewedBy                  sql.NullString `json:"reviewed_by"`
	ReviewedAt                  sql.NullInt64  `json:"reviewed_at"`
	SubscriptionID              sql.NullInt64  `json:"subscription_id"`
	IdempotencyKey              string         `json:"idempotency_key"`
	LastErrorKind               sql.NullString `json:"last_error_kind"`
	LastErrorMessage            sql.NullString `json:"last_error_message"`
	CreatedAt                   int64          `json:"created_at"`
	UpdatedAt                   int64          `json:"updated_at"`
}

type DiscoverySubscriptionRequestEvent struct {
	ID           int64          `json:"id"`
	RequestID    int64          `json:"request_id"`
	ActorUserID  sql.NullString `json:"actor_user_id"`
	Action       string         `json:"action"`
	FromStatus   sql.NullString `json:"from_status"`
	ToStatus     sql.NullString `json:"to_status"`
	Note         sql.NullString `json:"note"`
	SnapshotJson string         `json:"snapshot_json"`
	CreatedAt    int64          `json:"created_at"`
}

type DiscoveryUserAuditEvent struct {
	ID           int64          `json:"id"`
	ActorUserID  sql.NullString `json:"actor_user_id"`
	Action       string         `json:"action"`
	TargetKind   string         `json:"target_kind"`
	TargetID     sql.NullString `json:"target_id"`
	SafeReason   string         `json:"safe_reason"`
	SnapshotJson string         `json:"snapshot_json"`
	CreatedAt    int64          `json:"created_at"`
}

type EmbyItemMapping struct {
	ID                    int64          `json:"id"`
	EmbyServerID          string         `json:"emby_server_id"`
	EmbyItemID            string         `json:"emby_item_id"`
	MediaSourceID         string         `json:"media_source_id"`
	MappingID             int64          `json:"mapping_id"`
	MediaSourcePathRaw    string         `json:"media_source_path_raw"`
	MediaSourcePathNorm   string         `json:"media_source_path_norm"`
	PathNormVersion       int64          `json:"path_norm_version"`
	LibraryID             int64          `json:"library_id"`
	RelPath               string         `json:"rel_path"`
	LibraryEntryID        int64          `json:"library_entry_id"`
	BlobID                int64          `json:"blob_id"`
	LibraryEntryUpdatedAt int64          `json:"library_entry_updated_at"`
	EmbyItemEtag          sql.NullString `json:"emby_item_etag"`
	LastSeenAt            int64          `json:"last_seen_at"`
	CreatedAt             int64          `json:"created_at"`
	UpdatedAt             int64          `json:"updated_at"`
}

type EmbyLibraryMapping struct {
	ID                 int64  `json:"id"`
	EmbyServerID       string `json:"emby_server_id"`
	LibraryID          int64  `json:"library_id"`
	EmbyPathPrefix     string `json:"emby_path_prefix"`
	EmbyPathPrefixNorm string `json:"emby_path_prefix_norm"`
	EchoRelPrefix      string `json:"echo_rel_prefix"`
	CaseSensitive      int64  `json:"case_sensitive"`
	Enabled            int64  `json:"enabled"`
	CreatedAt          int64  `json:"created_at"`
	UpdatedAt          int64  `json:"updated_at"`
}

type EmbyServer struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	BaseUrl       string         `json:"base_url"`
	ApiKeyRef     sql.NullString `json:"api_key_ref"`
	PublicBaseUrl string         `json:"public_base_url"`
	ProxyPrefix   string         `json:"proxy_prefix"`
	Enabled       int64          `json:"enabled"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

type EmbyUserLink struct {
	ID           int64          `json:"id"`
	EmbyServerID string         `json:"emby_server_id"`
	EmbyUserID   string         `json:"emby_user_id"`
	EmbyUsername sql.NullString `json:"emby_username"`
	EchoUserID   string         `json:"echo_user_id"`
	Enabled      int64          `json:"enabled"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

type FileCopy struct {
	ID                    int64          `json:"id"`
	BlobID                int64          `json:"blob_id"`
	Provider              string         `json:"provider"`
	AccountID             string         `json:"account_id"`
	SidecarID             string         `json:"sidecar_id"`
	StorageMount          string         `json:"storage_mount"`
	RemotePath            string         `json:"remote_path"`
	CloudFileID           sql.NullString `json:"cloud_file_id"`
	Pickcode              sql.NullString `json:"pickcode"`
	Status                string         `json:"status"`
	LastSeen              int64          `json:"last_seen"`
	SchedulerState        string         `json:"scheduler_state"`
	CooldownUntil         sql.NullInt64  `json:"cooldown_until"`
	VerifyAfter           sql.NullInt64  `json:"verify_after"`
	FailureCount          int64          `json:"failure_count"`
	LastFailureAt         sql.NullInt64  `json:"last_failure_at"`
	LastFailureKind       sql.NullString `json:"last_failure_kind"`
	LastFailureConfidence sql.NullString `json:"last_failure_confidence"`
	LastFailureCode       sql.NullInt64  `json:"last_failure_code"`
	LastFailureMessage    sql.NullString `json:"last_failure_message"`
	DeadReason            sql.NullString `json:"dead_reason"`
	DeadAt                sql.NullInt64  `json:"dead_at"`
}

type HashConflict struct {
	ID         int64  `json:"id"`
	BlobIDA    int64  `json:"blob_id_a"`
	BlobIDB    int64  `json:"blob_id_b"`
	Reason     string `json:"reason"`
	Detail     string `json:"detail"`
	ObservedAt int64  `json:"observed_at"`
	Status     string `json:"status"`
}

type Job struct {
	ID         int64          `json:"id"`
	Kind       string         `json:"kind"`
	Status     string         `json:"status"`
	Payload    string         `json:"payload"`
	Progress   sql.NullString `json:"progress"`
	Error      sql.NullString `json:"error"`
	OwnerID    string         `json:"owner_id"`
	CreatedAt  int64          `json:"created_at"`
	StartedAt  sql.NullInt64  `json:"started_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
}

type Library struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	EchoOutputKind string `json:"echo_output_kind"`
	EchoOutputPath string `json:"echo_output_path"`
	OwnerID        string `json:"owner_id"`
	CreatedAt      int64  `json:"created_at"`
}

type LibraryEntry struct {
	ID          int64  `json:"id"`
	LibraryID   int64  `json:"library_id"`
	RelPath     string `json:"rel_path"`
	Name        string `json:"name"`
	BlobID      int64  `json:"blob_id"`
	EchoWritten int64  `json:"echo_written"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type LibraryGrant struct {
	ID         int64          `json:"id"`
	LibraryID  int64          `json:"library_id"`
	EchoUserID string         `json:"echo_user_id"`
	Permission string         `json:"permission"`
	Enabled    int64          `json:"enabled"`
	CreatedBy  sql.NullString `json:"created_by"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

type PlaybackErrorToken struct {
	ID            string         `json:"id"`
	Selector      string         `json:"selector"`
	TokenHash     string         `json:"token_hash"`
	EchoUserID    sql.NullString `json:"echo_user_id"`
	EmbyServerID  sql.NullString `json:"emby_server_id"`
	EmbyUserID    sql.NullString `json:"emby_user_id"`
	DeviceID      sql.NullString `json:"device_id"`
	ItemID        sql.NullString `json:"item_id"`
	MediaSourceID sql.NullString `json:"media_source_id"`
	Reason        string         `json:"reason"`
	HttpStatus    int64          `json:"http_status"`
	CreatedAt     int64          `json:"created_at"`
	ExpiresAt     int64          `json:"expires_at"`
}

type PlaybackEvent struct {
	ID             int64          `json:"id"`
	RequestID      string         `json:"request_id"`
	SessionID      sql.NullString `json:"session_id"`
	ErrorTokenID   sql.NullString `json:"error_token_id"`
	EchoUserID     sql.NullString `json:"echo_user_id"`
	LibraryEntryID sql.NullInt64  `json:"library_entry_id"`
	BlobID         sql.NullInt64  `json:"blob_id"`
	CopyID         sql.NullInt64  `json:"copy_id"`
	Provider       sql.NullString `json:"provider"`
	AccountID      sql.NullString `json:"account_id"`
	Operation      string         `json:"operation"`
	Status         string         `json:"status"`
	BytesSent      int64          `json:"bytes_sent"`
	RangeHeader    sql.NullString `json:"range_header"`
	HttpStatus     sql.NullInt64  `json:"http_status"`
	FailureKind    sql.NullString `json:"failure_kind"`
	FailureMessage sql.NullString `json:"failure_message"`
	StartedAt      int64          `json:"started_at"`
	FinishedAt     sql.NullInt64  `json:"finished_at"`
}

type PlaybackSession struct {
	ID                string         `json:"id"`
	Selector          string         `json:"selector"`
	TokenHash         string         `json:"token_hash"`
	EchoUserID        string         `json:"echo_user_id"`
	EmbyServerID      string         `json:"emby_server_id"`
	EmbyUserID        string         `json:"emby_user_id"`
	DeviceID          sql.NullString `json:"device_id"`
	ItemID            string         `json:"item_id"`
	MediaSourceID     string         `json:"media_source_id"`
	EmbyPlaySessionID sql.NullString `json:"emby_play_session_id"`
	LibraryEntryID    sql.NullInt64  `json:"library_entry_id"`
	BlobID            sql.NullInt64  `json:"blob_id"`
	PreferProvider    sql.NullString `json:"prefer_provider"`
	State             string         `json:"state"`
	FailureReason     sql.NullString `json:"failure_reason"`
	CreatedAt         int64          `json:"created_at"`
	LastSeenAt        int64          `json:"last_seen_at"`
	ExpiresAt         int64          `json:"expires_at"`
}

type ProducerRun struct {
	ID           int64          `json:"id"`
	JobID        int64          `json:"job_id"`
	Tool         string         `json:"tool"`
	ToolVersion  sql.NullString `json:"tool_version"`
	Cmdline      string         `json:"cmdline"`
	Workdir      string         `json:"workdir"`
	OutputDir    string         `json:"output_dir"`
	ManifestPath sql.NullString `json:"manifest_path"`
	StdoutPath   sql.NullString `json:"stdout_path"`
	StderrPath   sql.NullString `json:"stderr_path"`
	ExitCode     sql.NullInt64  `json:"exit_code"`
	StartedAt    int64          `json:"started_at"`
	FinishedAt   sql.NullInt64  `json:"finished_at"`
}

type QuotaPolicy struct {
	ID                  int64         `json:"id"`
	Name                string        `json:"name"`
	Period              string        `json:"period"`
	MaxBytes            sql.NullInt64 `json:"max_bytes"`
	MaxStreams          sql.NullInt64 `json:"max_streams"`
	MaxPlaybackSessions sql.NullInt64 `json:"max_playback_sessions"`
	Version             int64         `json:"version"`
	CreatedAt           int64         `json:"created_at"`
	UpdatedAt           int64         `json:"updated_at"`
}

type QuotaUsage struct {
	UserID        string `json:"user_id"`
	QuotaPolicyID int64  `json:"quota_policy_id"`
	PolicyVersion int64  `json:"policy_version"`
	PeriodStart   int64  `json:"period_start"`
	PeriodEnd     int64  `json:"period_end"`
	BytesUsed     int64  `json:"bytes_used"`
	StreamCount   int64  `json:"stream_count"`
	UpdatedAt     int64  `json:"updated_at"`
}

type RuleProfile struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Version   int64  `json:"version"`
	RulesJson string `json:"rules_json"`
	Enabled   int64  `json:"enabled"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type SubscriptionMatch struct {
	ID                   int64          `json:"id"`
	SubscriptionID       int64          `json:"subscription_id"`
	ResourceID           int64          `json:"resource_id"`
	RuleProfileID        int64          `json:"rule_profile_id"`
	RuleProfileVersion   int64          `json:"rule_profile_version"`
	SeasonNumber         sql.NullInt64  `json:"season_number"`
	EpisodeStart         sql.NullInt64  `json:"episode_start"`
	EpisodeEnd           sql.NullInt64  `json:"episode_end"`
	ScoreJson            string         `json:"score_json"`
	PreviousScoreJson    sql.NullString `json:"previous_score_json"`
	Decision             string         `json:"decision"`
	Reason               string         `json:"reason"`
	DispatchState        string         `json:"dispatch_state"`
	IdempotencyKey       string         `json:"idempotency_key"`
	QueuedJobID          sql.NullInt64  `json:"queued_job_id"`
	ResultLibraryEntryID sql.NullInt64  `json:"result_library_entry_id"`
	ResultBlobID         sql.NullInt64  `json:"result_blob_id"`
	ResultCopyID         sql.NullInt64  `json:"result_copy_id"`
	FailureKind          sql.NullString `json:"failure_kind"`
	FailureMessage       sql.NullString `json:"failure_message"`
	CreatedAt            int64          `json:"created_at"`
	UpdatedAt            int64          `json:"updated_at"`
	DecidedAt            sql.NullInt64  `json:"decided_at"`
	FinishedAt           sql.NullInt64  `json:"finished_at"`
}

type TelegramChannel struct {
	ID               int64          `json:"id"`
	SourceID         int64          `json:"source_id"`
	ChannelRef       string         `json:"channel_ref"`
	StablePeerID     sql.NullString `json:"stable_peer_id"`
	UsernameSnapshot sql.NullString `json:"username_snapshot"`
	TitleSnapshot    sql.NullString `json:"title_snapshot"`
	LevelFlags       int64          `json:"level_flags"`
	Enabled          int64          `json:"enabled"`
	LastMessageID    sql.NullInt64  `json:"last_message_id"`
	LastMessageDate  sql.NullInt64  `json:"last_message_date"`
	NextRunAt        sql.NullInt64  `json:"next_run_at"`
	LockedUntil      sql.NullInt64  `json:"locked_until"`
	BackoffUntil     sql.NullInt64  `json:"backoff_until"`
	FailureCount     int64          `json:"failure_count"`
	LastErrorKind    sql.NullString `json:"last_error_kind"`
	LastErrorMessage sql.NullString `json:"last_error_message"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

type TmdbMedium struct {
	ID               int64          `json:"id"`
	TmdbID           string         `json:"tmdb_id"`
	MediaType        string         `json:"media_type"`
	Language         string         `json:"language"`
	Title            string         `json:"title"`
	OriginalTitle    sql.NullString `json:"original_title"`
	ReleaseYear      sql.NullInt64  `json:"release_year"`
	PosterPath       sql.NullString `json:"poster_path"`
	Status           sql.NullString `json:"status"`
	RawJson          string         `json:"raw_json"`
	FetchedAt        int64          `json:"fetched_at"`
	NextRefreshAt    int64          `json:"next_refresh_at"`
	LastErrorKind    sql.NullString `json:"last_error_kind"`
	LastErrorMessage sql.NullString `json:"last_error_message"`
}

type User struct {
	ID            string         `json:"id"`
	Username      string         `json:"username"`
	Role          string         `json:"role"`
	Status        string         `json:"status"`
	QuotaPolicyID int64          `json:"quota_policy_id"`
	PasswordHash  sql.NullString `json:"password_hash"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
	LastLoginAt   sql.NullInt64  `json:"last_login_at"`
}

type UserMediaSubscription struct {
	ID                      int64          `json:"id"`
	EchoUserID              string         `json:"echo_user_id"`
	RequestID               sql.NullInt64  `json:"request_id"`
	DiscoverySubscriptionID int64          `json:"discovery_subscription_id"`
	TmdbID                  string         `json:"tmdb_id"`
	MediaType               string         `json:"media_type"`
	SeasonFilterJson        sql.NullString `json:"season_filter_json"`
	SeasonFilterKey         string         `json:"season_filter_key"`
	Status                  string         `json:"status"`
	CreatedAt               int64          `json:"created_at"`
	UpdatedAt               int64          `json:"updated_at"`
}
