// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Account struct {
	ID               string         `json:"id"`
	Provider         string         `json:"provider"`
	SidecarID        string         `json:"sidecar_id"`
	StorageMount     string         `json:"storage_mount"`
	Status           string         `json:"status"`
	LastCheck        sql.NullInt64  `json:"last_check"`
	OwnerID          string         `json:"owner_id"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	SchedulerState   string         `json:"scheduler_state"`
	CooldownUntil    sql.NullInt64  `json:"cooldown_until"`
	RecheckAfter     sql.NullInt64  `json:"recheck_after"`
	StatusReason     sql.NullString `json:"status_reason"`
	LastErrorAt      sql.NullInt64  `json:"last_error_at"`
	LastErrorKind    sql.NullString `json:"last_error_kind"`
	LastErrorMessage sql.NullString `json:"last_error_message"`
}

type ApiToken struct {
	ID         string        `json:"id"`
	UserID     string        `json:"user_id"`
	Name       string        `json:"name"`
	TokenHash  string        `json:"token_hash"`
	Scopes     string        `json:"scopes"`
	ExpiresAt  sql.NullInt64 `json:"expires_at"`
	LastUsedAt sql.NullInt64 `json:"last_used_at"`
	CreatedAt  int64         `json:"created_at"`
	RevokedAt  sql.NullInt64 `json:"revoked_at"`
}

type Blob struct {
	ID            int64          `json:"id"`
	Size          int64          `json:"size"`
	CanonicalName sql.NullString `json:"canonical_name"`
	SourceMtime   sql.NullInt64  `json:"source_mtime"`
	OwnerID       string         `json:"owner_id"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

type BlobHash struct {
	ID            int64  `json:"id"`
	BlobID        int64  `json:"blob_id"`
	HashType      string `json:"hash_type"`
	HashValue     string `json:"hash_value"`
	HashValueNorm string `json:"hash_value_norm"`
	Size          int64  `json:"size"`
}

type CopyFailure struct {
	ID            int64          `json:"id"`
	CopyID        sql.NullInt64  `json:"copy_id"`
	AccountID     sql.NullString `json:"account_id"`
	SidecarID     string         `json:"sidecar_id"`
	StorageMount  string         `json:"storage_mount"`
	Operation     string         `json:"operation"`
	Kind          string         `json:"kind"`
	Confidence    string         `json:"confidence"`
	EvidenceClass string         `json:"evidence_class"`
	HttpStatus    sql.NullInt64  `json:"http_status"`
	OpenlistCode  sql.NullInt64  `json:"openlist_code"`
	SafeMessage   sql.NullString `json:"safe_message"`
	ObservedAt    int64          `json:"observed_at"`
	RequestID     sql.NullString `json:"request_id"`
}

type FileCopy struct {
	ID                    int64          `json:"id"`
	BlobID                int64          `json:"blob_id"`
	Provider              string         `json:"provider"`
	AccountID             string         `json:"account_id"`
	SidecarID             string         `json:"sidecar_id"`
	StorageMount          string         `json:"storage_mount"`
	RemotePath            string         `json:"remote_path"`
	CloudFileID           sql.NullString `json:"cloud_file_id"`
	Pickcode              sql.NullString `json:"pickcode"`
	Status                string         `json:"status"`
	LastSeen              int64          `json:"last_seen"`
	SchedulerState        string         `json:"scheduler_state"`
	CooldownUntil         sql.NullInt64  `json:"cooldown_until"`
	VerifyAfter           sql.NullInt64  `json:"verify_after"`
	FailureCount          int64          `json:"failure_count"`
	LastFailureAt         sql.NullInt64  `json:"last_failure_at"`
	LastFailureKind       sql.NullString `json:"last_failure_kind"`
	LastFailureConfidence sql.NullString `json:"last_failure_confidence"`
	LastFailureCode       sql.NullInt64  `json:"last_failure_code"`
	LastFailureMessage    sql.NullString `json:"last_failure_message"`
	DeadReason            sql.NullString `json:"dead_reason"`
	DeadAt                sql.NullInt64  `json:"dead_at"`
}

type HashConflict struct {
	ID         int64  `json:"id"`
	BlobIDA    int64  `json:"blob_id_a"`
	BlobIDB    int64  `json:"blob_id_b"`
	Reason     string `json:"reason"`
	Detail     string `json:"detail"`
	ObservedAt int64  `json:"observed_at"`
	Status     string `json:"status"`
}

type Job struct {
	ID         int64          `json:"id"`
	Kind       string         `json:"kind"`
	Status     string         `json:"status"`
	Payload    string         `json:"payload"`
	Progress   sql.NullString `json:"progress"`
	Error      sql.NullString `json:"error"`
	OwnerID    string         `json:"owner_id"`
	CreatedAt  int64          `json:"created_at"`
	StartedAt  sql.NullInt64  `json:"started_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
}

type Library struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	EchoOutputKind string `json:"echo_output_kind"`
	EchoOutputPath string `json:"echo_output_path"`
	OwnerID        string `json:"owner_id"`
	CreatedAt      int64  `json:"created_at"`
}

type LibraryEntry struct {
	ID          int64  `json:"id"`
	LibraryID   int64  `json:"library_id"`
	RelPath     string `json:"rel_path"`
	Name        string `json:"name"`
	BlobID      int64  `json:"blob_id"`
	EchoWritten int64  `json:"echo_written"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type ProducerRun struct {
	ID           int64          `json:"id"`
	JobID        int64          `json:"job_id"`
	Tool         string         `json:"tool"`
	ToolVersion  sql.NullString `json:"tool_version"`
	Cmdline      string         `json:"cmdline"`
	Workdir      string         `json:"workdir"`
	OutputDir    string         `json:"output_dir"`
	ManifestPath sql.NullString `json:"manifest_path"`
	StdoutPath   sql.NullString `json:"stdout_path"`
	StderrPath   sql.NullString `json:"stderr_path"`
	ExitCode     sql.NullInt64  `json:"exit_code"`
	StartedAt    int64          `json:"started_at"`
	FinishedAt   sql.NullInt64  `json:"finished_at"`
}

type User struct {
	ID           string         `json:"id"`
	Username     string         `json:"username"`
	Role         string         `json:"role"`
	Status       string         `json:"status"`
	PasswordHash sql.NullString `json:"password_hash"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
	LastLoginAt  sql.NullInt64  `json:"last_login_at"`
}
