// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Account struct {
	ID           string        `json:"id"`
	Provider     string        `json:"provider"`
	SidecarID    string        `json:"sidecar_id"`
	StorageMount string        `json:"storage_mount"`
	Status       string        `json:"status"`
	LastCheck    sql.NullInt64 `json:"last_check"`
	OwnerID      string        `json:"owner_id"`
	CreatedAt    int64         `json:"created_at"`
	UpdatedAt    int64         `json:"updated_at"`
}

type Blob struct {
	ID            int64          `json:"id"`
	Size          int64          `json:"size"`
	CanonicalName sql.NullString `json:"canonical_name"`
	SourceMtime   sql.NullInt64  `json:"source_mtime"`
	OwnerID       string         `json:"owner_id"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

type BlobHash struct {
	ID            int64  `json:"id"`
	BlobID        int64  `json:"blob_id"`
	HashType      string `json:"hash_type"`
	HashValue     string `json:"hash_value"`
	HashValueNorm string `json:"hash_value_norm"`
	Size          int64  `json:"size"`
}

type FileCopy struct {
	ID           int64          `json:"id"`
	BlobID       int64          `json:"blob_id"`
	Provider     string         `json:"provider"`
	AccountID    string         `json:"account_id"`
	SidecarID    string         `json:"sidecar_id"`
	StorageMount string         `json:"storage_mount"`
	RemotePath   string         `json:"remote_path"`
	CloudFileID  sql.NullString `json:"cloud_file_id"`
	Pickcode     sql.NullString `json:"pickcode"`
	Status       string         `json:"status"`
	LastSeen     int64          `json:"last_seen"`
}

type HashConflict struct {
	ID         int64  `json:"id"`
	BlobIDA    int64  `json:"blob_id_a"`
	BlobIDB    int64  `json:"blob_id_b"`
	Reason     string `json:"reason"`
	Detail     string `json:"detail"`
	ObservedAt int64  `json:"observed_at"`
	Status     string `json:"status"`
}

type Job struct {
	ID         int64          `json:"id"`
	Kind       string         `json:"kind"`
	Status     string         `json:"status"`
	Payload    string         `json:"payload"`
	Progress   sql.NullString `json:"progress"`
	Error      sql.NullString `json:"error"`
	OwnerID    string         `json:"owner_id"`
	CreatedAt  int64          `json:"created_at"`
	StartedAt  sql.NullInt64  `json:"started_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
}

type Library struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	EchoOutputKind string `json:"echo_output_kind"`
	EchoOutputPath string `json:"echo_output_path"`
	OwnerID        string `json:"owner_id"`
	CreatedAt      int64  `json:"created_at"`
}

type LibraryEntry struct {
	ID          int64  `json:"id"`
	LibraryID   int64  `json:"library_id"`
	RelPath     string `json:"rel_path"`
	Name        string `json:"name"`
	BlobID      int64  `json:"blob_id"`
	EchoWritten int64  `json:"echo_written"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type ProducerRun struct {
	ID           int64          `json:"id"`
	JobID        int64          `json:"job_id"`
	Tool         string         `json:"tool"`
	ToolVersion  sql.NullString `json:"tool_version"`
	Cmdline      string         `json:"cmdline"`
	Workdir      string         `json:"workdir"`
	OutputDir    string         `json:"output_dir"`
	ManifestPath sql.NullString `json:"manifest_path"`
	StdoutPath   sql.NullString `json:"stdout_path"`
	StderrPath   sql.NullString `json:"stderr_path"`
	ExitCode     sql.NullInt64  `json:"exit_code"`
	StartedAt    int64          `json:"started_at"`
	FinishedAt   sql.NullInt64  `json:"finished_at"`
}
