// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playback_management.sql

package queries

import (
	"context"
	"database/sql"
)

const countActivePlaybackSessions = `-- name: CountActivePlaybackSessions :one
SELECT COUNT(*)
FROM playback_sessions
WHERE state = 'active'
  AND expires_at > unixepoch()
`

func (q *Queries) CountActivePlaybackSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivePlaybackSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getQuotaUsageFromEvents = `-- name: GetQuotaUsageFromEvents :one
SELECT
  COALESCE(SUM(bytes_sent), 0) AS bytes_used,
  COUNT(*) AS stream_count
FROM playback_events
WHERE echo_user_id = ?
  AND operation = 'stream'
  AND status IN ('ok','interrupted','failed','upstream_read_error')
  AND bytes_sent > 0
  AND started_at >= ?
  AND started_at < ?
`

type GetQuotaUsageFromEventsParams struct {
	EchoUserID  sql.NullString `json:"echo_user_id"`
	StartedAt   int64          `json:"started_at"`
	StartedAt_2 int64          `json:"started_at_2"`
}

type GetQuotaUsageFromEventsRow struct {
	BytesUsed   interface{} `json:"bytes_used"`
	StreamCount int64       `json:"stream_count"`
}

func (q *Queries) GetQuotaUsageFromEvents(ctx context.Context, arg GetQuotaUsageFromEventsParams) (GetQuotaUsageFromEventsRow, error) {
	row := q.db.QueryRowContext(ctx, getQuotaUsageFromEvents, arg.EchoUserID, arg.StartedAt, arg.StartedAt_2)
	var i GetQuotaUsageFromEventsRow
	err := row.Scan(&i.BytesUsed, &i.StreamCount)
	return i, err
}

const listAccountPoolAssignments = `-- name: ListAccountPoolAssignments :many
SELECT id, echo_user_id, account_id, provider, priority, weight, max_concurrent_streams, daily_bytes_limit, enabled, created_at, updated_at FROM account_pool_assignments
WHERE (? = '' OR echo_user_id = ?)
ORDER BY echo_user_id, provider, priority, account_id
LIMIT ? OFFSET ?
`

type ListAccountPoolAssignmentsParams struct {
	Column1    interface{} `json:"column_1"`
	EchoUserID string      `json:"echo_user_id"`
	Limit      int64       `json:"limit"`
	Offset     int64       `json:"offset"`
}

func (q *Queries) ListAccountPoolAssignments(ctx context.Context, arg ListAccountPoolAssignmentsParams) ([]AccountPoolAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listAccountPoolAssignments,
		arg.Column1,
		arg.EchoUserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountPoolAssignment
	for rows.Next() {
		var i AccountPoolAssignment
		if err := rows.Scan(
			&i.ID,
			&i.EchoUserID,
			&i.AccountID,
			&i.Provider,
			&i.Priority,
			&i.Weight,
			&i.MaxConcurrentStreams,
			&i.DailyBytesLimit,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaybackEventsForAdmin = `-- name: ListPlaybackEventsForAdmin :many
SELECT id, request_id, session_id, error_token_id, echo_user_id, library_entry_id, blob_id, copy_id, provider, account_id, operation, status, bytes_sent, range_header, http_status, failure_kind, failure_message, started_at, finished_at FROM playback_events
WHERE (? = '' OR echo_user_id = ?)
ORDER BY started_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListPlaybackEventsForAdminParams struct {
	Column1    interface{}    `json:"column_1"`
	EchoUserID sql.NullString `json:"echo_user_id"`
	Limit      int64          `json:"limit"`
	Offset     int64          `json:"offset"`
}

func (q *Queries) ListPlaybackEventsForAdmin(ctx context.Context, arg ListPlaybackEventsForAdminParams) ([]PlaybackEvent, error) {
	rows, err := q.db.QueryContext(ctx, listPlaybackEventsForAdmin,
		arg.Column1,
		arg.EchoUserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaybackEvent
	for rows.Next() {
		var i PlaybackEvent
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.SessionID,
			&i.ErrorTokenID,
			&i.EchoUserID,
			&i.LibraryEntryID,
			&i.BlobID,
			&i.CopyID,
			&i.Provider,
			&i.AccountID,
			&i.Operation,
			&i.Status,
			&i.BytesSent,
			&i.RangeHeader,
			&i.HttpStatus,
			&i.FailureKind,
			&i.FailureMessage,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaybackEventsForUser = `-- name: ListPlaybackEventsForUser :many
SELECT id, request_id, session_id, error_token_id, echo_user_id, library_entry_id, blob_id, copy_id, provider, account_id, operation, status, bytes_sent, range_header, http_status, failure_kind, failure_message, started_at, finished_at FROM playback_events
WHERE echo_user_id = ?
ORDER BY started_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListPlaybackEventsForUserParams struct {
	EchoUserID sql.NullString `json:"echo_user_id"`
	Limit      int64          `json:"limit"`
	Offset     int64          `json:"offset"`
}

func (q *Queries) ListPlaybackEventsForUser(ctx context.Context, arg ListPlaybackEventsForUserParams) ([]PlaybackEvent, error) {
	rows, err := q.db.QueryContext(ctx, listPlaybackEventsForUser, arg.EchoUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaybackEvent
	for rows.Next() {
		var i PlaybackEvent
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.SessionID,
			&i.ErrorTokenID,
			&i.EchoUserID,
			&i.LibraryEntryID,
			&i.BlobID,
			&i.CopyID,
			&i.Provider,
			&i.AccountID,
			&i.Operation,
			&i.Status,
			&i.BytesSent,
			&i.RangeHeader,
			&i.HttpStatus,
			&i.FailureKind,
			&i.FailureMessage,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaybackSessionsForAdmin = `-- name: ListPlaybackSessionsForAdmin :many
SELECT id, selector, token_hash, echo_user_id, emby_server_id, emby_user_id, device_id, item_id, media_source_id, emby_play_session_id, library_entry_id, blob_id, prefer_provider, state, failure_reason, created_at, last_seen_at, expires_at FROM playback_sessions
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListPlaybackSessionsForAdminParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListPlaybackSessionsForAdmin(ctx context.Context, arg ListPlaybackSessionsForAdminParams) ([]PlaybackSession, error) {
	rows, err := q.db.QueryContext(ctx, listPlaybackSessionsForAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaybackSession
	for rows.Next() {
		var i PlaybackSession
		if err := rows.Scan(
			&i.ID,
			&i.Selector,
			&i.TokenHash,
			&i.EchoUserID,
			&i.EmbyServerID,
			&i.EmbyUserID,
			&i.DeviceID,
			&i.ItemID,
			&i.MediaSourceID,
			&i.EmbyPlaySessionID,
			&i.LibraryEntryID,
			&i.BlobID,
			&i.PreferProvider,
			&i.State,
			&i.FailureReason,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaybackSessionsForUser = `-- name: ListPlaybackSessionsForUser :many
SELECT id, selector, token_hash, echo_user_id, emby_server_id, emby_user_id, device_id, item_id, media_source_id, emby_play_session_id, library_entry_id, blob_id, prefer_provider, state, failure_reason, created_at, last_seen_at, expires_at FROM playback_sessions
WHERE echo_user_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListPlaybackSessionsForUserParams struct {
	EchoUserID string `json:"echo_user_id"`
	Limit      int64  `json:"limit"`
	Offset     int64  `json:"offset"`
}

func (q *Queries) ListPlaybackSessionsForUser(ctx context.Context, arg ListPlaybackSessionsForUserParams) ([]PlaybackSession, error) {
	rows, err := q.db.QueryContext(ctx, listPlaybackSessionsForUser, arg.EchoUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaybackSession
	for rows.Next() {
		var i PlaybackSession
		if err := rows.Scan(
			&i.ID,
			&i.Selector,
			&i.TokenHash,
			&i.EchoUserID,
			&i.EmbyServerID,
			&i.EmbyUserID,
			&i.DeviceID,
			&i.ItemID,
			&i.MediaSourceID,
			&i.EmbyPlaySessionID,
			&i.LibraryEntryID,
			&i.BlobID,
			&i.PreferProvider,
			&i.State,
			&i.FailureReason,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuotaPolicy = `-- name: UpdateQuotaPolicy :one
UPDATE quota_policies
SET
  name = ?,
  period = ?,
  max_bytes = ?,
  max_streams = ?,
  max_playback_sessions = ?,
  version = version + 1,
  updated_at = ?
WHERE id = ?
RETURNING id, name, period, max_bytes, max_streams, max_playback_sessions, version, created_at, updated_at
`

type UpdateQuotaPolicyParams struct {
	Name                string        `json:"name"`
	Period              string        `json:"period"`
	MaxBytes            sql.NullInt64 `json:"max_bytes"`
	MaxStreams          sql.NullInt64 `json:"max_streams"`
	MaxPlaybackSessions sql.NullInt64 `json:"max_playback_sessions"`
	UpdatedAt           int64         `json:"updated_at"`
	ID                  int64         `json:"id"`
}

func (q *Queries) UpdateQuotaPolicy(ctx context.Context, arg UpdateQuotaPolicyParams) (QuotaPolicy, error) {
	row := q.db.QueryRowContext(ctx, updateQuotaPolicy,
		arg.Name,
		arg.Period,
		arg.MaxBytes,
		arg.MaxStreams,
		arg.MaxPlaybackSessions,
		arg.UpdatedAt,
		arg.ID,
	)
	var i QuotaPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Period,
		&i.MaxBytes,
		&i.MaxStreams,
		&i.MaxPlaybackSessions,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAccountPoolAssignment = `-- name: UpsertAccountPoolAssignment :one
INSERT INTO account_pool_assignments (
  echo_user_id, account_id, provider, priority, weight, max_concurrent_streams,
  daily_bytes_limit, enabled, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(echo_user_id, account_id) DO UPDATE SET
  provider = excluded.provider,
  priority = excluded.priority,
  weight = excluded.weight,
  max_concurrent_streams = excluded.max_concurrent_streams,
  daily_bytes_limit = excluded.daily_bytes_limit,
  enabled = excluded.enabled,
  updated_at = excluded.updated_at
RETURNING id, echo_user_id, account_id, provider, priority, weight, max_concurrent_streams, daily_bytes_limit, enabled, created_at, updated_at
`

type UpsertAccountPoolAssignmentParams struct {
	EchoUserID           string        `json:"echo_user_id"`
	AccountID            string        `json:"account_id"`
	Provider             string        `json:"provider"`
	Priority             int64         `json:"priority"`
	Weight               int64         `json:"weight"`
	MaxConcurrentStreams sql.NullInt64 `json:"max_concurrent_streams"`
	DailyBytesLimit      sql.NullInt64 `json:"daily_bytes_limit"`
	Enabled              int64         `json:"enabled"`
	CreatedAt            int64         `json:"created_at"`
	UpdatedAt            int64         `json:"updated_at"`
}

func (q *Queries) UpsertAccountPoolAssignment(ctx context.Context, arg UpsertAccountPoolAssignmentParams) (AccountPoolAssignment, error) {
	row := q.db.QueryRowContext(ctx, upsertAccountPoolAssignment,
		arg.EchoUserID,
		arg.AccountID,
		arg.Provider,
		arg.Priority,
		arg.Weight,
		arg.MaxConcurrentStreams,
		arg.DailyBytesLimit,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AccountPoolAssignment
	err := row.Scan(
		&i.ID,
		&i.EchoUserID,
		&i.AccountID,
		&i.Provider,
		&i.Priority,
		&i.Weight,
		&i.MaxConcurrentStreams,
		&i.DailyBytesLimit,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
