// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playback_sessions.sql

package queries

import (
	"context"
	"database/sql"
)

const createPlaybackSession = `-- name: CreatePlaybackSession :exec
INSERT INTO playback_sessions (
  id, selector, token_hash, echo_user_id, emby_server_id, emby_user_id, device_id,
  item_id, media_source_id, emby_play_session_id, library_entry_id, blob_id,
  prefer_provider, state, failure_reason, created_at, last_seen_at, expires_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreatePlaybackSessionParams struct {
	ID                string         `json:"id"`
	Selector          string         `json:"selector"`
	TokenHash         string         `json:"token_hash"`
	EchoUserID        string         `json:"echo_user_id"`
	EmbyServerID      string         `json:"emby_server_id"`
	EmbyUserID        string         `json:"emby_user_id"`
	DeviceID          sql.NullString `json:"device_id"`
	ItemID            string         `json:"item_id"`
	MediaSourceID     string         `json:"media_source_id"`
	EmbyPlaySessionID sql.NullString `json:"emby_play_session_id"`
	LibraryEntryID    sql.NullInt64  `json:"library_entry_id"`
	BlobID            sql.NullInt64  `json:"blob_id"`
	PreferProvider    sql.NullString `json:"prefer_provider"`
	State             string         `json:"state"`
	FailureReason     sql.NullString `json:"failure_reason"`
	CreatedAt         int64          `json:"created_at"`
	LastSeenAt        int64          `json:"last_seen_at"`
	ExpiresAt         int64          `json:"expires_at"`
}

func (q *Queries) CreatePlaybackSession(ctx context.Context, arg CreatePlaybackSessionParams) error {
	_, err := q.db.ExecContext(ctx, createPlaybackSession,
		arg.ID,
		arg.Selector,
		arg.TokenHash,
		arg.EchoUserID,
		arg.EmbyServerID,
		arg.EmbyUserID,
		arg.DeviceID,
		arg.ItemID,
		arg.MediaSourceID,
		arg.EmbyPlaySessionID,
		arg.LibraryEntryID,
		arg.BlobID,
		arg.PreferProvider,
		arg.State,
		arg.FailureReason,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
	)
	return err
}

const getPlaybackSessionBySelector = `-- name: GetPlaybackSessionBySelector :one
SELECT id, selector, token_hash, echo_user_id, emby_server_id, emby_user_id, device_id, item_id, media_source_id, emby_play_session_id, library_entry_id, blob_id, prefer_provider, state, failure_reason, created_at, last_seen_at, expires_at FROM playback_sessions
WHERE selector = ?
`

type GetPlaybackSessionBySelectorParams struct {
	Selector string `json:"selector"`
}

func (q *Queries) GetPlaybackSessionBySelector(ctx context.Context, arg GetPlaybackSessionBySelectorParams) (PlaybackSession, error) {
	row := q.db.QueryRowContext(ctx, getPlaybackSessionBySelector, arg.Selector)
	var i PlaybackSession
	err := row.Scan(
		&i.ID,
		&i.Selector,
		&i.TokenHash,
		&i.EchoUserID,
		&i.EmbyServerID,
		&i.EmbyUserID,
		&i.DeviceID,
		&i.ItemID,
		&i.MediaSourceID,
		&i.EmbyPlaySessionID,
		&i.LibraryEntryID,
		&i.BlobID,
		&i.PreferProvider,
		&i.State,
		&i.FailureReason,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const revokePlaybackSession = `-- name: RevokePlaybackSession :exec
UPDATE playback_sessions
SET state = 'revoked', failure_reason = ?, last_seen_at = ?
WHERE id = ?
`

type RevokePlaybackSessionParams struct {
	FailureReason sql.NullString `json:"failure_reason"`
	LastSeenAt    int64          `json:"last_seen_at"`
	ID            string         `json:"id"`
}

func (q *Queries) RevokePlaybackSession(ctx context.Context, arg RevokePlaybackSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokePlaybackSession, arg.FailureReason, arg.LastSeenAt, arg.ID)
	return err
}

const touchPlaybackSession = `-- name: TouchPlaybackSession :exec
UPDATE playback_sessions
SET last_seen_at = ?
WHERE id = ?
`

type TouchPlaybackSessionParams struct {
	LastSeenAt int64  `json:"last_seen_at"`
	ID         string `json:"id"`
}

func (q *Queries) TouchPlaybackSession(ctx context.Context, arg TouchPlaybackSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchPlaybackSession, arg.LastSeenAt, arg.ID)
	return err
}
