// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playback_events.sql

package queries

import (
	"context"
	"database/sql"
)

const finishPlaybackEvent = `-- name: FinishPlaybackEvent :exec
UPDATE playback_events
SET status = ?, bytes_sent = ?, http_status = ?, failure_kind = ?, failure_message = ?, finished_at = ?
WHERE id = ? AND operation = 'stream' AND finished_at IS NULL
`

type FinishPlaybackEventParams struct {
	Status         string         `json:"status"`
	BytesSent      int64          `json:"bytes_sent"`
	HttpStatus     sql.NullInt64  `json:"http_status"`
	FailureKind    sql.NullString `json:"failure_kind"`
	FailureMessage sql.NullString `json:"failure_message"`
	FinishedAt     sql.NullInt64  `json:"finished_at"`
	ID             int64          `json:"id"`
}

func (q *Queries) FinishPlaybackEvent(ctx context.Context, arg FinishPlaybackEventParams) error {
	_, err := q.db.ExecContext(ctx, finishPlaybackEvent,
		arg.Status,
		arg.BytesSent,
		arg.HttpStatus,
		arg.FailureKind,
		arg.FailureMessage,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const insertPlaybackEvent = `-- name: InsertPlaybackEvent :one
INSERT INTO playback_events (
  request_id, session_id, error_token_id, echo_user_id, library_entry_id, blob_id,
  copy_id, provider, account_id, operation, status, bytes_sent, range_header,
  http_status, failure_kind, failure_message, started_at, finished_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id
`

type InsertPlaybackEventParams struct {
	RequestID      string         `json:"request_id"`
	SessionID      sql.NullString `json:"session_id"`
	ErrorTokenID   sql.NullString `json:"error_token_id"`
	EchoUserID     sql.NullString `json:"echo_user_id"`
	LibraryEntryID sql.NullInt64  `json:"library_entry_id"`
	BlobID         sql.NullInt64  `json:"blob_id"`
	CopyID         sql.NullInt64  `json:"copy_id"`
	Provider       sql.NullString `json:"provider"`
	AccountID      sql.NullString `json:"account_id"`
	Operation      string         `json:"operation"`
	Status         string         `json:"status"`
	BytesSent      int64          `json:"bytes_sent"`
	RangeHeader    sql.NullString `json:"range_header"`
	HttpStatus     sql.NullInt64  `json:"http_status"`
	FailureKind    sql.NullString `json:"failure_kind"`
	FailureMessage sql.NullString `json:"failure_message"`
	StartedAt      int64          `json:"started_at"`
	FinishedAt     sql.NullInt64  `json:"finished_at"`
}

func (q *Queries) InsertPlaybackEvent(ctx context.Context, arg InsertPlaybackEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPlaybackEvent,
		arg.RequestID,
		arg.SessionID,
		arg.ErrorTokenID,
		arg.EchoUserID,
		arg.LibraryEntryID,
		arg.BlobID,
		arg.CopyID,
		arg.Provider,
		arg.AccountID,
		arg.Operation,
		arg.Status,
		arg.BytesSent,
		arg.RangeHeader,
		arg.HttpStatus,
		arg.FailureKind,
		arg.FailureMessage,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listActiveStreamEventIDs = `-- name: ListActiveStreamEventIDs :many
SELECT id
FROM playback_events
WHERE echo_user_id = ?
  AND operation = 'stream'
  AND finished_at IS NULL
  AND started_at >= ?
ORDER BY started_at DESC
`

type ListActiveStreamEventIDsParams struct {
	EchoUserID sql.NullString `json:"echo_user_id"`
	StartedAt  int64          `json:"started_at"`
}

func (q *Queries) ListActiveStreamEventIDs(ctx context.Context, arg ListActiveStreamEventIDsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listActiveStreamEventIDs, arg.EchoUserID, arg.StartedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStalePlaybackEventsInterrupted = `-- name: MarkStalePlaybackEventsInterrupted :exec
UPDATE playback_events
SET status = 'interrupted',
    failure_kind = 'process_reconcile',
    finished_at = ?
WHERE operation = 'stream'
  AND finished_at IS NULL
  AND started_at < ?
`

type MarkStalePlaybackEventsInterruptedParams struct {
	FinishedAt sql.NullInt64 `json:"finished_at"`
	StartedAt  int64         `json:"started_at"`
}

func (q *Queries) MarkStalePlaybackEventsInterrupted(ctx context.Context, arg MarkStalePlaybackEventsInterruptedParams) error {
	_, err := q.db.ExecContext(ctx, markStalePlaybackEventsInterrupted, arg.FinishedAt, arg.StartedAt)
	return err
}

const sumPlaybackBytesInWindow = `-- name: SumPlaybackBytesInWindow :one
SELECT CAST(COALESCE(SUM(bytes_sent), 0) AS INTEGER) AS bytes
FROM playback_events
WHERE echo_user_id = ?
  AND operation = 'stream'
  AND started_at >= ?
  AND started_at < ?
  AND bytes_sent > 0
  AND status IN ('ok','interrupted','failed','upstream_read_error')
`

type SumPlaybackBytesInWindowParams struct {
	EchoUserID  sql.NullString `json:"echo_user_id"`
	StartedAt   int64          `json:"started_at"`
	StartedAt_2 int64          `json:"started_at_2"`
}

func (q *Queries) SumPlaybackBytesInWindow(ctx context.Context, arg SumPlaybackBytesInWindowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumPlaybackBytesInWindow, arg.EchoUserID, arg.StartedAt, arg.StartedAt_2)
	var bytes int64
	err := row.Scan(&bytes)
	return bytes, err
}
