// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playback_error_tokens.sql

package queries

import (
	"context"
	"database/sql"
)

const createPlaybackErrorToken = `-- name: CreatePlaybackErrorToken :exec
INSERT INTO playback_error_tokens (
  id, selector, token_hash, echo_user_id, emby_server_id, emby_user_id, device_id,
  item_id, media_source_id, reason, http_status, created_at, expires_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreatePlaybackErrorTokenParams struct {
	ID            string         `json:"id"`
	Selector      string         `json:"selector"`
	TokenHash     string         `json:"token_hash"`
	EchoUserID    sql.NullString `json:"echo_user_id"`
	EmbyServerID  sql.NullString `json:"emby_server_id"`
	EmbyUserID    sql.NullString `json:"emby_user_id"`
	DeviceID      sql.NullString `json:"device_id"`
	ItemID        sql.NullString `json:"item_id"`
	MediaSourceID sql.NullString `json:"media_source_id"`
	Reason        string         `json:"reason"`
	HttpStatus    int64          `json:"http_status"`
	CreatedAt     int64          `json:"created_at"`
	ExpiresAt     int64          `json:"expires_at"`
}

func (q *Queries) CreatePlaybackErrorToken(ctx context.Context, arg CreatePlaybackErrorTokenParams) error {
	_, err := q.db.ExecContext(ctx, createPlaybackErrorToken,
		arg.ID,
		arg.Selector,
		arg.TokenHash,
		arg.EchoUserID,
		arg.EmbyServerID,
		arg.EmbyUserID,
		arg.DeviceID,
		arg.ItemID,
		arg.MediaSourceID,
		arg.Reason,
		arg.HttpStatus,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const getPlaybackErrorTokenBySelector = `-- name: GetPlaybackErrorTokenBySelector :one
SELECT id, selector, token_hash, echo_user_id, emby_server_id, emby_user_id, device_id, item_id, media_source_id, reason, http_status, created_at, expires_at FROM playback_error_tokens
WHERE selector = ?
`

type GetPlaybackErrorTokenBySelectorParams struct {
	Selector string `json:"selector"`
}

func (q *Queries) GetPlaybackErrorTokenBySelector(ctx context.Context, arg GetPlaybackErrorTokenBySelectorParams) (PlaybackErrorToken, error) {
	row := q.db.QueryRowContext(ctx, getPlaybackErrorTokenBySelector, arg.Selector)
	var i PlaybackErrorToken
	err := row.Scan(
		&i.ID,
		&i.Selector,
		&i.TokenHash,
		&i.EchoUserID,
		&i.EmbyServerID,
		&i.EmbyUserID,
		&i.DeviceID,
		&i.ItemID,
		&i.MediaSourceID,
		&i.Reason,
		&i.HttpStatus,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
