// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: producer_runs.sql

package queries

import (
	"context"
	"database/sql"
)

const createProducerRun = `-- name: CreateProducerRun :one
INSERT INTO producer_runs (
  job_id, tool, tool_version, cmdline, workdir, output_dir, manifest_path,
  stdout_path, stderr_path, exit_code, started_at, finished_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, job_id, tool, tool_version, cmdline, workdir, output_dir, manifest_path, stdout_path, stderr_path, exit_code, started_at, finished_at
`

type CreateProducerRunParams struct {
	JobID        int64          `json:"job_id"`
	Tool         string         `json:"tool"`
	ToolVersion  sql.NullString `json:"tool_version"`
	Cmdline      string         `json:"cmdline"`
	Workdir      string         `json:"workdir"`
	OutputDir    string         `json:"output_dir"`
	ManifestPath sql.NullString `json:"manifest_path"`
	StdoutPath   sql.NullString `json:"stdout_path"`
	StderrPath   sql.NullString `json:"stderr_path"`
	ExitCode     sql.NullInt64  `json:"exit_code"`
	StartedAt    int64          `json:"started_at"`
	FinishedAt   sql.NullInt64  `json:"finished_at"`
}

func (q *Queries) CreateProducerRun(ctx context.Context, arg CreateProducerRunParams) (ProducerRun, error) {
	row := q.db.QueryRowContext(ctx, createProducerRun,
		arg.JobID,
		arg.Tool,
		arg.ToolVersion,
		arg.Cmdline,
		arg.Workdir,
		arg.OutputDir,
		arg.ManifestPath,
		arg.StdoutPath,
		arg.StderrPath,
		arg.ExitCode,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i ProducerRun
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Tool,
		&i.ToolVersion,
		&i.Cmdline,
		&i.Workdir,
		&i.OutputDir,
		&i.ManifestPath,
		&i.StdoutPath,
		&i.StderrPath,
		&i.ExitCode,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishProducerRun = `-- name: FinishProducerRun :exec
UPDATE producer_runs
SET exit_code = ?,
    finished_at = ?,
    manifest_path = COALESCE(?, manifest_path),
    stdout_path = COALESCE(?, stdout_path),
    stderr_path = COALESCE(?, stderr_path)
WHERE id = ?
`

type FinishProducerRunParams struct {
	ExitCode     sql.NullInt64  `json:"exit_code"`
	FinishedAt   sql.NullInt64  `json:"finished_at"`
	ManifestPath sql.NullString `json:"manifest_path"`
	StdoutPath   sql.NullString `json:"stdout_path"`
	StderrPath   sql.NullString `json:"stderr_path"`
	ID           int64          `json:"id"`
}

func (q *Queries) FinishProducerRun(ctx context.Context, arg FinishProducerRunParams) error {
	_, err := q.db.ExecContext(ctx, finishProducerRun,
		arg.ExitCode,
		arg.FinishedAt,
		arg.ManifestPath,
		arg.StdoutPath,
		arg.StderrPath,
		arg.ID,
	)
	return err
}

const getProducerRun = `-- name: GetProducerRun :one
SELECT id, job_id, tool, tool_version, cmdline, workdir, output_dir, manifest_path, stdout_path, stderr_path, exit_code, started_at, finished_at FROM producer_runs
WHERE id = ?
`

type GetProducerRunParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetProducerRun(ctx context.Context, arg GetProducerRunParams) (ProducerRun, error) {
	row := q.db.QueryRowContext(ctx, getProducerRun, arg.ID)
	var i ProducerRun
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Tool,
		&i.ToolVersion,
		&i.Cmdline,
		&i.Workdir,
		&i.OutputDir,
		&i.ManifestPath,
		&i.StdoutPath,
		&i.StderrPath,
		&i.ExitCode,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listProducerRunsByJob = `-- name: ListProducerRunsByJob :many
SELECT id, job_id, tool, tool_version, cmdline, workdir, output_dir, manifest_path, stdout_path, stderr_path, exit_code, started_at, finished_at FROM producer_runs
WHERE job_id = ?
ORDER BY id
`

type ListProducerRunsByJobParams struct {
	JobID int64 `json:"job_id"`
}

func (q *Queries) ListProducerRunsByJob(ctx context.Context, arg ListProducerRunsByJobParams) ([]ProducerRun, error) {
	rows, err := q.db.QueryContext(ctx, listProducerRunsByJob, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProducerRun
	for rows.Next() {
		var i ProducerRun
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Tool,
			&i.ToolVersion,
			&i.Cmdline,
			&i.Workdir,
			&i.OutputDir,
			&i.ManifestPath,
			&i.StdoutPath,
			&i.StderrPath,
			&i.ExitCode,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
