// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quota_policies.sql

package queries

import (
	"context"
	"database/sql"
)

const createQuotaPolicy = `-- name: CreateQuotaPolicy :one
INSERT INTO quota_policies (
  name, period, max_bytes, max_streams, max_playback_sessions, version, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, 1, ?, ?
)
RETURNING id, name, period, max_bytes, max_streams, max_playback_sessions, version, created_at, updated_at
`

type CreateQuotaPolicyParams struct {
	Name                string        `json:"name"`
	Period              string        `json:"period"`
	MaxBytes            sql.NullInt64 `json:"max_bytes"`
	MaxStreams          sql.NullInt64 `json:"max_streams"`
	MaxPlaybackSessions sql.NullInt64 `json:"max_playback_sessions"`
	CreatedAt           int64         `json:"created_at"`
	UpdatedAt           int64         `json:"updated_at"`
}

func (q *Queries) CreateQuotaPolicy(ctx context.Context, arg CreateQuotaPolicyParams) (QuotaPolicy, error) {
	row := q.db.QueryRowContext(ctx, createQuotaPolicy,
		arg.Name,
		arg.Period,
		arg.MaxBytes,
		arg.MaxStreams,
		arg.MaxPlaybackSessions,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i QuotaPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Period,
		&i.MaxBytes,
		&i.MaxStreams,
		&i.MaxPlaybackSessions,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuotaPolicy = `-- name: GetQuotaPolicy :one
SELECT id, name, period, max_bytes, max_streams, max_playback_sessions, version, created_at, updated_at FROM quota_policies WHERE id = ?
`

type GetQuotaPolicyParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetQuotaPolicy(ctx context.Context, arg GetQuotaPolicyParams) (QuotaPolicy, error) {
	row := q.db.QueryRowContext(ctx, getQuotaPolicy, arg.ID)
	var i QuotaPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Period,
		&i.MaxBytes,
		&i.MaxStreams,
		&i.MaxPlaybackSessions,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuotaPolicies = `-- name: ListQuotaPolicies :many
SELECT id, name, period, max_bytes, max_streams, max_playback_sessions, version, created_at, updated_at FROM quota_policies ORDER BY id LIMIT ? OFFSET ?
`

type ListQuotaPoliciesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListQuotaPolicies(ctx context.Context, arg ListQuotaPoliciesParams) ([]QuotaPolicy, error) {
	rows, err := q.db.QueryContext(ctx, listQuotaPolicies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuotaPolicy
	for rows.Next() {
		var i QuotaPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Period,
			&i.MaxBytes,
			&i.MaxStreams,
			&i.MaxPlaybackSessions,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
