// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package queries

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
  id, username, role, status, quota_policy_id, password_hash, created_at, updated_at, last_login_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateUserParams struct {
	ID            string         `json:"id"`
	Username      string         `json:"username"`
	Role          string         `json:"role"`
	Status        string         `json:"status"`
	QuotaPolicyID int64          `json:"quota_policy_id"`
	PasswordHash  sql.NullString `json:"password_hash"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
	LastLoginAt   sql.NullInt64  `json:"last_login_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Role,
		arg.Status,
		arg.QuotaPolicyID,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastLoginAt,
	)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, role, status, quota_policy_id, password_hash, created_at, updated_at, last_login_at FROM users WHERE id = ?
`

type GetUserParams struct {
	ID string `json:"id"`
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Status,
		&i.QuotaPolicyID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, role, status, quota_policy_id, password_hash, created_at, updated_at, last_login_at FROM users WHERE username = ?
`

type GetUserByUsernameParams struct {
	Username string `json:"username"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, arg GetUserByUsernameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Status,
		&i.QuotaPolicyID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, role, status, quota_policy_id, password_hash, created_at, updated_at, last_login_at FROM users
ORDER BY username
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Status,
			&i.QuotaPolicyID,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET status = ?, updated_at = ?
WHERE id = ?
`

type UpdateUserStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
